#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Oaww.Entity;
    using Oaww.Entity.SET;
    using Oaww.HtmlHelp;
    using Oaww.Utility;
    using Oaww.ViewModel;
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Lang;
    using Oaww.ViewModel.Search;
    using Oaww.ViewModel.SiteMap;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/Model/IndexSetting.cshtml")]
    public partial class _Areas_webadmin_Views_Model_IndexSetting_cshtml : System.Web.Mvc.WebViewPage<PageIndexSetting>
    {
        public _Areas_webadmin_Views_Model_IndexSetting_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
  
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--page bar start-->\r\n<div");

WriteLiteral(" class=\"page-bar\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 203), Tuple.Create("\"", 237)
            
            #line 9 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
, Tuple.Create(Tuple.Create("", 210), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 210), false)
);

WriteLiteral(">Home</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 334), Tuple.Create("\"", 369)
            
            #line 13 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
, Tuple.Create(Tuple.Create("", 341), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Model")
            
            #line default
            #line hidden
, 341), false)
);

WriteLiteral(">模組設定</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n    </ul>\r\n</div>\r\n<!--page bar end-->\r\n<!--message start--" +
">\r\n<div");

WriteLiteral(" class=\"title_01\"");

WriteLiteral(">全文檢索管理</div>\r\n<form");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral(" id=\"editform\"");

WriteAttribute("action", Tuple.Create(" action=\'", 607), Tuple.Create("\'", 647)
            
            #line 21 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
 , Tuple.Create(Tuple.Create("", 616), Tuple.Create<System.Object, System.Int32>(Url.Action("SaveIndexSetting")
            
            #line default
            #line hidden
, 616), false)
);

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
Write(Html.HiddenFor(Model => Model.ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(" id=\"div_seo\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(" id=\"form-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group hide\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-2 col-sm-2 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">檢索說明</div>\r\n                        <div");

WriteLiteral(" class=\"col-md-10 col-sm-10 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                            <textarea");

WriteLiteral(" cols=\"80\"");

WriteLiteral(" id=\"HtmlContent\"");

WriteLiteral(" rows=\"20\"");

WriteLiteral(">");

            
            #line 30 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
                                                                      Write(HttpUtility.HtmlDecode(Model.HtmlContent));

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                        </div>\r\n                    </div>\r\n        " +
"            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-2 col-sm-2 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">熱門關鍵字</div>\r\n                        <div");

WriteLiteral(" class=\"col-md-10 col-sm-10 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" class=\"input_inline\"");

WriteLiteral(">\r\n                                <li> ");

            
            #line 37 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
                                Write(Html.EditorFor(model => model.HotKey1, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                                <li>");

            
            #line 38 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
                               Write(Html.EditorFor(model => model.HotKey2, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                                <li>");

            
            #line 39 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
                               Write(Html.EditorFor(model => model.HotKey3, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                            </ul>\r\n                        </div>\r\n       " +
"             </div>\r\n                    <div");

WriteLiteral(" class=\"form-group hide\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-2 col-sm-2 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">每頁顯示筆數</div>\r\n                        <div");

WriteLiteral(" class=\"col-md-4 col-sm-4 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                            <select");

WriteLiteral(" class=\"form_02\"");

WriteLiteral(" id=\"ShowCount\"");

WriteLiteral(" name=\"ShowCount\"");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" value=\"10\"");

WriteLiteral(">10</option>\r\n                                <option");

WriteLiteral(" value=\"30\"");

WriteLiteral(">30</option>\r\n                                <option");

WriteLiteral(" value=\"50\"");

WriteLiteral(">50</option>\r\n                                <option");

WriteLiteral(" value=\"100\"");

WriteLiteral(">100</option>\r\n                            </select>\r\n                        </d" +
"iv>\r\n                        <div");

WriteLiteral(" class=\"col-md-6 col-sm-6 hidden-xs bg-white\"");

WriteLiteral(">&nbsp;</div>\r\n                    </div>\r\n\r\n\r\n                </div>\r\n\r\n        " +
"    </div>\r\n\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"text-center search_padding\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(">確認送出</button>\r\n    </div>\r\n</form>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3176), Tuple.Create("\"", 3220)
            
            #line 68 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
, Tuple.Create(Tuple.Create("", 3182), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/datatable.js")
            
            #line default
            #line hidden
, 3182), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3244), Tuple.Create("\"", 3285)
            
            #line 69 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
, Tuple.Create(Tuple.Create("", 3250), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/custom.js")
            
            #line default
            #line hidden
, 3250), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3309), Tuple.Create("\"", 3361)
            
            #line 70 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
, Tuple.Create(Tuple.Create("", 3315), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ckeditor/ckeditor.js")
            
            #line default
            #line hidden
, 3315), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3385), Tuple.Create("\"", 3409)
, Tuple.Create(Tuple.Create("", 3391), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/_html.js")
, 3391), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            $(\"#ShowCount\").va" +
"l(\'");

            
            #line 74 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
                            Write(Model.ShowCount);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n\r\n             var ckedit = CKEDITOR.replace(\'HtmlContent\', {\r\n             " +
"       height: 300,\r\n                    filebrowserImageUploadUrl: \'");

            
            #line 78 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
                                           Write(Url.Action("Upload"));

            
            #line default
            #line hidden
WriteLiteral(@"?command=QuickUpload&type=Images'
                });

                CKEDITOR.config.enterMode = CKEDITOR.ENTER_BR;
                CKEDITOR.config.shiftEnterMode = CKEDITOR.ENTER_P;
                CKEDITOR.on('instanceReady', function (ev) {
                    ev.editor.dataProcessor.writer.setRules('p',
                        {
                            indent: false,
                            breakBeforeOpen: false,
                            breakAfterOpen: false,
                            breakBeforeClose: false,
                            breakAfterClose: false
                        });
                });

            $('#editform').submit(function (event) {

                var formData = new FormData();
                var array = $('#editform').serializeArray();
                //formData.append(""HtmlContent"", _html.encode(CKEDITOR.instances.HtmlContent.getData()));
                $.each(array, function () {
                    formData.append(this.name, this.value);
                });

                $.ajax({
                    url: this.action,
                    type: ""Post"",
                    data: formData,
                    headers: {
                        RequestVerificationToken: '");

            
            #line 108 "..\..\Areas\webadmin\Views\Model\IndexSetting.cshtml"
                                              Write(CommonRazorFunctions.GetAntiForgery());

            
            #line default
            #line hidden
WriteLiteral(@"'
                    },
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (result) {
                        alert(result);
                        if (result == ""設定成功"") {
                            location.reload();
                        }

                    }
                });
                return false;
            })
        });
    </script>

");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
