#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Oaww.Entity;
    using Oaww.Entity.SET;
    using Oaww.HtmlHelp;
    using Oaww.Utility;
    using Oaww.ViewModel;
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Lang;
    using Oaww.ViewModel.Search;
    using Oaww.ViewModel.SiteMap;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/Config/SiteLangEdit.cshtml")]
    public partial class _Areas_webadmin_Views_Config_SiteLangEdit_cshtml : System.Web.Mvc.WebViewPage<SiteLangModel>
    {
        public _Areas_webadmin_Views_Config_SiteLangEdit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
  
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--page bar start-->\r\n<div");

WriteLiteral(" class=\"page-bar all_width\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <span");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Home</span>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n            <span");

WriteLiteral(" href=\"#\"");

WriteLiteral(">系統權限管理</span>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n            <span");

WriteLiteral(" href=\"#\"");

WriteLiteral(">多國語系設定</span>\r\n        </li>\r\n    </ul>\r\n</div>\r\n<!--page bar end-->\r\n<!--messag" +
"e start-->\r\n<div");

WriteLiteral(" class=\"title_01\"");

WriteLiteral(">多國語系設定</div>\r\n<div");

WriteLiteral(" class=\"portlet light bordered\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral(" id=\"editform\"");

WriteAttribute("action", Tuple.Create(" action=\'", 630), Tuple.Create("\'", 662)
            
            #line 21 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
     , Tuple.Create(Tuple.Create("", 639), Tuple.Create<System.Object, System.Int32>(Url.Action("SaveLang")
            
            #line default
            #line hidden
, 639), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 22 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(" id=\"form-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 27 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                   Write(Html.HiddenFor(model => model.ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-2 col-xs-12 search_item\"");

WriteLiteral("><span");

WriteLiteral(" class=\"red\"");

WriteLiteral(">*</span>語系</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-4 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 31 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                           Write(Html.EditorFor(model => model.Lang_Name, new { htmlAttributes = new { @class = "form-control checkitem" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"Lang_Name-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">語系 必須填寫！</span>\r\n                            </div>\r\n                        </d" +
"iv>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-2 col-xs-12 search_item\"");

WriteLiteral("><span");

WriteLiteral(" class=\"red\"");

WriteLiteral(">*</span>前台語系顯示文字</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-4 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 38 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                           Write(Html.EditorFor(model => model.Disp_Name, new { htmlAttributes = new { @class = "form-control checkitem" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"Disp_Name-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">前台語系顯示文字 必須填寫！</span>\r\n                            </div>\r\n                     " +
"   </div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-2 col-xs-12 search_item\"");

WriteLiteral("><span");

WriteLiteral(" class=\"red\"");

WriteLiteral(">*</span>網址</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-4 col-xs-12 bg-white mobile_white form_blank\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 45 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                           Write(Html.EditorFor(model => model.Sub_Domain_Name, new { htmlAttributes = new { @class = "form-control checkitem" } }));

            
            #line default
            #line hidden
WriteLiteral(" .DomainName.com.tw\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"Sub_Domain_Name-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">網址 必須填寫！</span>\r\n                            </div>\r\n                        </d" +
"iv>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-2 col-xs-12 search_item\"");

WriteLiteral(">內容來源方式</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-4 col-xs-12 bg-white mobile_white form_blank\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">");

            
            #line 52 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                                            Write(Html.RadioButtonFor(model => model.Domain_Type, 1, new { style = "margin-left :10px", @checked = "checked" }));

            
            #line default
            #line hidden
WriteLiteral(" 自行建立</div>\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"width:100%;margin-top:3px\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 54 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                               Write(Html.RadioButtonFor(model => model.Domain_Type, 2, new { style = "margin-left :10px;float:left" }));

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" style=\"float:left;margin-left :10px\"");

WriteLiteral(">連結其他語系</span>\r\n");

WriteLiteral("                                    ");

            
            #line 55 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                               Write(Html.DropDownList(@Html.IdFor(m => m.Link_Lang_ID).ToString(), (IEnumerable<SelectListItem>)ViewBag.langlist, new { @class = "form-control", style = "float:left;margin-left :10px;width:200px" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"width:100%;margin-top:3px\"");

WriteLiteral(">");

            
            #line 58 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                                                                              Write(Html.RadioButtonFor(model => model.Domain_Type, 3, new { style = "margin-left :10px;float:left" }));

            
            #line default
            #line hidden
WriteLiteral(" <span");

WriteLiteral(" style=\"float:left;margin-left :10px\"");

WriteLiteral(">連結其他網址</span> ");

            
            #line 58 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                                                                                                                                                                                                                                           Write(Html.EditorFor(model => model.Link_Href, new { htmlAttributes = new { @class = "form-control", style = "float:left;width:300px;margin-left :10px" } }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n                            </div>\r\n                        </div>\r\n\r\n " +
"                   </div>\r\n                </div>\r\n            </div>\r\n        <" +
"/div>\r\n\r\n        <div");

WriteLiteral(" class=\"text-center search_padding\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(">確認送出</button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn grey-mint\"");

WriteLiteral(" id=\"btn_return\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 4536), Tuple.Create("\"", 4594)
, Tuple.Create(Tuple.Create("", 4546), Tuple.Create("document.location.href=\'", 4546), true)
            
            #line 70 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                         , Tuple.Create(Tuple.Create("", 4570), Tuple.Create<System.Object, System.Int32>(Url.Action("SiteLang")
            
            #line default
            #line hidden
, 4570), false)
, Tuple.Create(Tuple.Create("", 4593), Tuple.Create("\'", 4593), true)
);

WriteLiteral(">返回列表</button>\r\n        </div>\r\n    </form>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script>\r\n        $(function () {\r\n            if (\'");

            
            #line 77 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
            Write(ViewBag.disableadd);

            
            #line default
            #line hidden
WriteLiteral(@"'=='Y') {
                $('#btn_submit').hide();
            }
            $('#editform').submit(function (event) {
                var inputval = $(""#form-body :input"").filter(function () { return $(this).val() == """" && $(this).hasClass('checkitem'); });
                    for (var idx = 0; idx < inputval.length; idx++) {
                        $(""#"" + inputval[idx].name + ""-error"").show();
                    }
                    if (inputval.length > 0) { return false; }

                    $.ajax({
                        url: this.action,
                        type: this.method,
                        data: $(this).serialize(),
                        success: function (result) {
                            if (result == """") {
                                alert(""儲存成功"");
                                document.location.href = '");

            
            #line 94 "..\..\Areas\webadmin\Views\Config\SiteLangEdit.cshtml"
                                                     Write(Url.Action("SiteLang"));

            
            #line default
            #line hidden
WriteLiteral("\'\r\n                            } else {\r\n                                alert(re" +
"sult);\r\n                            }\r\n                        }\r\n              " +
"     });\r\n                    return false;\r\n            })\r\n        });\r\n    </" +
"script>\r\n\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
