#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\webadmin\Views\Menu\MenuLinkEdit.cshtml"
    using Oaww.Entity;
    
    #line default
    #line hidden
    using Oaww.Entity.SET;
    using Oaww.HtmlHelp;
    using Oaww.Utility;
    using Oaww.ViewModel;
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Search;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/Menu/MenuLinkEdit.cshtml")]
    public partial class _Areas_webadmin_Views_Menu_MenuLinkEdit_cshtml : System.Web.Mvc.WebViewPage<Menu>
    {
        public _Areas_webadmin_Views_Menu_MenuLinkEdit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Areas\webadmin\Views\Menu\MenuLinkEdit.cshtml"
  
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    .btn i {\r\n        margin-left: 0px;\r\n    }\r\n</style>\r\n<div");

WriteLiteral(" class=\"page-bar\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 259), Tuple.Create("\"", 293)
            
            #line 15 "..\..\Areas\webadmin\Views\Menu\MenuLinkEdit.cshtml"
, Tuple.Create(Tuple.Create("", 266), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 266), false)
);

WriteLiteral(">Home</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">網站選單</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 23 "..\..\Areas\webadmin\Views\Menu\MenuLinkEdit.cshtml"
                   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </li>\r\n    </ul>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"title_01\"");

WriteLiteral(">");

            
            #line 28 "..\..\Areas\webadmin\Views\Menu\MenuLinkEdit.cshtml"
                  Write(string.IsNullOrEmpty(Model.DisplayName) ? Model.MenuName : Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<div");

WriteLiteral(" class=\"portlet light bordered\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral(" id=\"editform\"");

WriteAttribute("action", Tuple.Create(" action=\'", 785), Tuple.Create("\'", 825)
            
            #line 31 "..\..\Areas\webadmin\Views\Menu\MenuLinkEdit.cshtml"
     , Tuple.Create(Tuple.Create("", 794), Tuple.Create<System.Object, System.Int32>(Url.Action("SaveMenuLinkEdit")
            
            #line default
            #line hidden
, 794), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Areas\webadmin\Views\Menu\MenuLinkEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(" id=\"div_seo\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(" id=\"form-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">連結路徑</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 40 "..\..\Areas\webadmin\Views\Menu\MenuLinkEdit.cshtml"
                           Write(Html.EditorFor(model => model.LinkUrl, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"MenuName-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">連結路徑 必須填寫！</span>\r\n                            </div>\r\n                        <" +
"/div>\r\n                    </div>\r\n\r\n                </div>\r\n\r\n            </div" +
">\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"text-center search_padding\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(">確認送出</button>\r\n        </div>\r\n    </form>\r\n");

DefineSection("scripts", () => {

            
            #line 54 "..\..\Areas\webadmin\Views\Menu\MenuLinkEdit.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral(@"
        <script>
        $(function () {

            $('#editform').submit(function (event) {
               $("".required"").hide();
               var inputval = $(""#editform :input"").filter(function () { return $(this).val() == """" && $(this).hasClass('checkitem'); });
                for (var idx = 0; idx < inputval.length; idx++) {
                    $(""#"" + inputval[idx].name + ""-error"").show();
                }
                if (inputval.length > 0) { return false; }
                var formData = new FormData();

                formData.append(""linkurl"", $(""#LinkUrl"").val());
                formData.append(""menuid"", ");

            
            #line 68 "..\..\Areas\webadmin\Views\Menu\MenuLinkEdit.cshtml"
                                     Write(Model.ID);

            
            #line default
            #line hidden
WriteLiteral(@");
                debugger
                $.ajax({
                    url: this.action,
                    data: formData,
                    type: 'POST',
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        alert(data);
                    }, error: function () {
                        // handle error
                    }
                });
                return false;
            });
        });
        </script>

    ");

});

WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
