#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Oaww.Entity;
    using Oaww.Entity.SET;
    
    #line 2 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
    using Oaww.HtmlHelp;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
    using Oaww.Utility;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
    using Oaww.ViewModel;
    
    #line default
    #line hidden
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Lang;
    using Oaww.ViewModel.Search;
    using Oaww.ViewModel.SiteMap;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/Menu/MenuEdit.cshtml")]
    public partial class _Areas_webadmin_Views_Menu_MenuEdit_cshtml : System.Web.Mvc.WebViewPage<MenuEditModel>
    {
        public _Areas_webadmin_Views_Menu_MenuEdit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
  
    List<SelectListItem> ListModel = (List<SelectListItem>)ViewData["ListModel"];
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 253), Tuple.Create("\"", 294)
            
            #line 10 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
, Tuple.Create(Tuple.Create("", 259), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/custom.js")
            
            #line default
            #line hidden
, 259), false)
);

WriteLiteral("></script>\r\n<!--page bar start-->\r\n<div");

WriteLiteral(" class=\"page-bar all_width\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 426), Tuple.Create("\"", 460)
            
            #line 15 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
, Tuple.Create(Tuple.Create("", 433), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 433), false)
);

WriteLiteral(">Home</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">網站選單</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 662), Tuple.Create("\"", 724)
            
            #line 23 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
, Tuple.Create(Tuple.Create("", 669), Tuple.Create<System.Object, System.Int32>(Url.Action("MainMenu","Menu")
            
            #line default
            #line hidden
, 669), false)
, Tuple.Create(Tuple.Create("", 699), Tuple.Create("?menutype=", 699), true)
            
            #line 23 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
, Tuple.Create(Tuple.Create("", 709), Tuple.Create<System.Object, System.Int32>(Model.MenuType
            
            #line default
            #line hidden
, 709), false)
);

WriteLiteral(">");

            
            #line 23 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                         Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </li>\r\n    </ul>\r\n</div>\r\n<!--page bar end-->\r\n<!--message start-->" +
"\r\n<div");

WriteLiteral(" class=\"title_01\"");

WriteLiteral(">");

            
            #line 29 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                  Write(Model.ID == 0 ? "新增選單" : "修改選單");

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div");

WriteLiteral(" class=\"portlet light bordered\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral(" id=\"editform\"");

WriteAttribute("action", Tuple.Create(" action=\'", 1000), Tuple.Create("\'", 1032)
            
            #line 31 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
    , Tuple.Create(Tuple.Create("", 1009), Tuple.Create<System.Object, System.Int32>(Url.Action("SaveMenu")
            
            #line default
            #line hidden
, 1009), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 33 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.MenuType));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 34 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ImgNameOri));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 35 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.MenuLevel));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 36 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ParentID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 37 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.DeleteUploadFile));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 38 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.LinkUploadFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(" id=\"div_seo\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(" id=\"form-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">");

            
            #line 44 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                                       Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 選單名稱</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" id=\"MenuName\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control checkitem\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1995), Tuple.Create("\"", 2018)
            
            #line 46 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                       , Tuple.Create(Tuple.Create("", 2003), Tuple.Create<System.Object, System.Int32>(Model.MenuName
            
            #line default
            #line hidden
, 2003), false)
);

WriteLiteral(" />\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"MenuName-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">選單內容 必須填寫！</span>\r\n                            </div>\r\n                        <" +
"/div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral("> 選單英文名稱</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" name=\"DisplayName\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control \"");

WriteAttribute("value", Tuple.Create(" value=\"", 2551), Tuple.Create("\"", 2577)
            
            #line 53 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                   , Tuple.Create(Tuple.Create("", 2559), Tuple.Create<System.Object, System.Int32>(Model.DisplayName
            
            #line default
            #line hidden
, 2559), false)
);

WriteLiteral(" />\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"DisplayName-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">選單內容 必須填寫！</span>\r\n                            </div>\r\n                        <" +
"/div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">顯示名稱</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 60 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                           Write(Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">Icon</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 66 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                           Write(Html.EditorFor(model => model.Icon, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral(">內頁風格圖片</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" id=\"div_oldfile\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4047), Tuple.Create("\"", 4069)
            
            #line 73 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
        , Tuple.Create(Tuple.Create("", 4054), Tuple.Create<System.Object, System.Int32>(Model.ImageUrl
            
            #line default
            #line hidden
, 4054), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(">");

            
            #line 73 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                                                                     Write(Html.Raw(Model.ImgShowName.safeHtmlFragment()));

            
            #line default
            #line hidden
WriteLiteral("</a><label");

WriteLiteral(" style=\"color:blue;margin-left:10px;cursor:pointer\"");

WriteLiteral(" id=\"delimage\"");

WriteLiteral(">刪除</label></div>\r\n                                    <div");

WriteLiteral(" style=\"display:inline\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" id=\"file_image\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(" name=\"ImageFile\"");

WriteLiteral(" accept=\"image/*\"");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"    <div>\r\n                                        <span");

WriteLiteral(" style=\"color:red;padding-left; font-size:12px\"");

WriteLiteral(">建議尺寸 960(w) X 210(h) pixels，限jpg、gif、png格式</span>\r\n                             " +
"       </div>\r\n                                </div>\r\n                         " +
"       ");

WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral(">");

            
            #line 88 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                   Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 連結方式</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\r\n                                    <label");

WriteLiteral(" for=\"ImageFile\"");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">連結方式</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 94 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                   Write(Html.RadioButtonFor(model => model.LinkMode, 1, new { style = "margin-left :15px", @checked = "checked", @class = "LinkMode" }));

            
            #line default
            #line hidden
WriteLiteral(" 無\r\n");

WriteLiteral("                                        ");

            
            #line 95 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                   Write(Html.RadioButtonFor(model => model.LinkMode, 2, new { style = "margin-left :40px", @class = "LinkMode" }));

            
            #line default
            #line hidden
WriteLiteral(" 程式模組\r\n");

WriteLiteral("                                        ");

            
            #line 96 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                   Write(Html.RadioButtonFor(model => model.LinkMode, 3, new { style = "margin-left :40px", @class = "LinkMode" }));

            
            #line default
            #line hidden
WriteLiteral(" 路徑\r\n");

WriteLiteral("                                        ");

            
            #line 97 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                   Write(Html.RadioButtonFor(model => model.LinkMode, 4, new { style = "margin-left :40px", @class = "LinkMode" }));

            
            #line default
            #line hidden
WriteLiteral(" 檔案\r\n                                    </div>\r\n                                " +
"</div>\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" id=\"div_model\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" for=\"ImageFile\"");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">程式模組</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <select");

WriteLiteral(" style=\"\"");

WriteLiteral(" id=\"sel_model\"");

WriteAttribute("name", Tuple.Create(" name=\'", 6665), Tuple.Create("\'", 6697)
            
            #line 103 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
, Tuple.Create(Tuple.Create("", 6672), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m=>m.ModelID)
            
            #line default
            #line hidden
, 6672), false)
);

WriteLiteral(" class=\"form-control_1\"");

WriteLiteral(">\r\n                                            <option");

WriteLiteral(" value=\"\"");

WriteLiteral(" selected=\"selected\"");

WriteLiteral(">");

            
            #line 104 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                            Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral("請選擇程式模組</option>\r\n");

            
            #line 105 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 105 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                             foreach (var m in ListModel)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 7015), Tuple.Create("\"", 7031)
            
            #line 107 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
, Tuple.Create(Tuple.Create("", 7023), Tuple.Create<System.Object, System.Int32>(m.Value
            
            #line default
            #line hidden
, 7023), false)
);

WriteLiteral(">");

            
            #line 107 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                    Write(m.Text);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 108 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </select>\r\n                              " +
"          <select");

WriteLiteral(" style=\"margin-left :10px\"");

WriteLiteral(" id=\"sel_modelitem\"");

WriteAttribute("name", Tuple.Create(" name=\'", 7241), Tuple.Create("\'", 7277)
            
            #line 110 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                   , Tuple.Create(Tuple.Create("", 7248), Tuple.Create<System.Object, System.Int32>(Html.IdFor(m=>m.ModelItemID)
            
            #line default
            #line hidden
, 7248), false)
);

WriteLiteral(" class=\"form-control_1\"");

WriteLiteral("></select>\r\n                                    </div>\r\n\r\n\r\n                     " +
"           </div>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" id=\"div_link\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" for=\"ImageFile\"");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">");

            
            #line 117 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                       Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 連結路徑</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 119 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                   Write(Html.EditorFor(model => model.LinkUrl, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"LinkUrl-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">選單內容 必須填寫！</span>\r\n                                    </div>\r\n                 " +
"               </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(" id=\"div_file\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" id=\"div_hasfile\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n\r\n                                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn blue-hoki alert_box_checkbox\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" id=\'btn_DelFile\'");

WriteLiteral(">刪除</a>\r\n                                        <label");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">檔案名稱</label>\r\n                                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                            <a");

WriteAttribute("href", Tuple.Create(" href=\'", 8504), Tuple.Create("\'", 8556)
            
            #line 129 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
, Tuple.Create(Tuple.Create("", 8511), Tuple.Create<System.Object, System.Int32>(Url.Action("FileDownLoad",new {id=Model.ID})
            
            #line default
            #line hidden
, 8511), false)
);

WriteLiteral(">");

            
            #line 129 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                                               Write(Model.LinkUploadFileName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        </div>\r\n                           " +
"         </div>\r\n                                    <div");

WriteLiteral(" id=\"div_nofile\"");

WriteLiteral(" style=\"display:inline\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">檔案上傳</label>\r\n                                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"uploadfile\"");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(" name=\"uploadfile\"");

WriteLiteral(">\r\n                                        </div>\r\n                              " +
"      </div>\r\n                                </div>\r\n                          " +
"  </div>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">");

            
            #line 142 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                                       Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 顯示模式</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white form-horizontal table" +
"_font\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 144 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                           Write(Html.RadioButtonFor(model => model.ShowMode, 1, new { style = "margin-left :0px", @checked = "checked" }));

            
            #line default
            #line hidden
WriteLiteral(" 顯示框架\r\n");

WriteLiteral("                                ");

            
            #line 145 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                           Write(Html.RadioButtonFor(model => model.ShowMode, 2, new { style = "margin-left :40px" }));

            
            #line default
            #line hidden
WriteLiteral(" 不顯示框架\r\n                            </div>\r\n                        </div>\r\n     " +
"                   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">前台是否呈現</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white form-horizontal table" +
"_font\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 151 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                           Write(Html.CheckBoxFor(model => model.FrontDisplay.Value, new { @id = "FrontDisplay", @name = "FrontDisplay" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">");

            
            #line 155 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                                       Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 開啟方式</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white form-horizontal\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 157 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                           Write(Html.RadioButtonFor(model => model.OpenMode, 1, new { style = "margin-left :0px", @checked = "checked" }));

            
            #line default
            #line hidden
WriteLiteral(" 原視窗<br />\r\n");

WriteLiteral("                                ");

            
            #line 158 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                           Write(Html.RadioButtonFor(model => model.OpenMode, 2, new { style = "" }));

            
            #line default
            #line hidden
WriteLiteral(" 新視窗<br />\r\n");

WriteLiteral("                                ");

            
            #line 159 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                           Write(Html.RadioButtonFor(model => model.OpenMode, 3, new { style = "float:left" }));

            
            #line default
            #line hidden
WriteLiteral(" <div");

WriteLiteral(" style=\"float:left\"");

WriteLiteral(">跳出視窗</div>\r\n                                <div>\r\n                             " +
"       <div");

WriteLiteral(" style=\"float:left; margin-left:40px\"");

WriteLiteral(">視窗寬度</div>");

            
            #line 161 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                                   Write(Html.EditorFor(model => model.WindowWidth, new { htmlAttributes = new { @class = "form-control input-small", style = "float:left; margin-left:2px" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <div");

WriteLiteral(" style=\"float:left;margin-left:20px\"");

WriteLiteral(">視窗高度</div>");

            
            #line 162 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                                  Write(Html.EditorFor(model => model.WindowHeight, new { htmlAttributes = new { @class = "form-control input-small", style = "float:left;margin-left:2px" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                    </div>\r\n\r\n                </div" +
">\r\n\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"text-center search_padding\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(">確認送出</button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn grey-cascade\"");

WriteLiteral(" id=\"btn_return\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 11962), Tuple.Create("\"", 12036)
, Tuple.Create(Tuple.Create("", 11972), Tuple.Create("location.href=\'", 11972), true)
            
            #line 174 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                  , Tuple.Create(Tuple.Create("", 11987), Tuple.Create<System.Object, System.Int32>(Url.Action("MainMenu")
            
            #line default
            #line hidden
, 11987), false)
, Tuple.Create(Tuple.Create("", 12010), Tuple.Create("?menutype=", 12010), true)
            
            #line 174 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                   , Tuple.Create(Tuple.Create("", 12020), Tuple.Create<System.Object, System.Int32>(Model.MenuType
            
            #line default
            #line hidden
, 12020), false)
, Tuple.Create(Tuple.Create("", 12035), Tuple.Create("\'", 12035), true)
);

WriteLiteral(">取消</button>\r\n        </div>\r\n    </form>\r\n");

DefineSection("scripts", () => {

            
            #line 177 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral("\r\n        <script");

WriteAttribute("src", Tuple.Create(" src=\"", 12119), Tuple.Create("\"", 12143)
, Tuple.Create(Tuple.Create("", 12125), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/_html.js")
, 12125), false)
);

WriteLiteral("></script>\r\n        <script>\r\n        $(function () {\r\n            var fileupload" +
" = \'");

            
            #line 181 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                         Write(Model.ImageFile);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n          if (\'");

            
            #line 182 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
          Write(Model.ID);

            
            #line default
            #line hidden
WriteLiteral("\'>0 && \'");

            
            #line 182 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                           Write(Model.ImgNameOri);

            
            #line default
            #line hidden
WriteLiteral("\'!=\'\') {\r\n                $(\'#div_oldfile\').show();\r\n            }\r\n\r\n");

            
            #line 186 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
            
            
            #line default
            #line hidden
            
            #line 186 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
             if (string.IsNullOrEmpty(Model.LinkUploadFileName) == false && Model.DeleteUploadFile == "N")
              {
            
            #line default
            #line hidden
WriteLiteral("$(\"#div_hasfile\").show(); $(\"#div_nofile\").hide(); ");

            
            #line 187 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                               }

            
            #line default
            #line hidden
WriteLiteral(@"
            $('#delimage').click(function () {
                $('#div_oldfile').hide();
                $('#ImgNameOri').val('');
            });
            $(""#btn_DelFile"").click(function () {
                $(""#DeleteUploadFile"").val('Y');
                $(""#LinkUploadFileName"").val('');
                $(""#div_hasfile"").hide(); $(""#div_nofile"").show();
            });

            if ('");

            
            #line 199 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
            Write(Model.LinkMode);

            
            #line default
            #line hidden
WriteLiteral("\' == 2) {\r\n                if (\'");

            
            #line 200 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                Write(Model.ModelID);

            
            #line default
            #line hidden
WriteLiteral("\' != \'0\') {\r\n                    $(\'#sel_model\').val(\'");

            
            #line 201 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                    Write(Model.ModelID);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n                    $.post(\'");

            
            #line 202 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                       Write(Url.Action("GetModelItem"));

            
            #line default
            #line hidden
WriteLiteral("\', {\r\n                        \"modelid\": $(\'#sel_model\').val(),\r\n                " +
"        \'menutype\': \'");

            
            #line 204 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                Write(Model.MenuType);

            
            #line default
            #line hidden
WriteLiteral("\'\r\n                    }, function (data) {\r\n                        $(data).appe" +
"ndTo(\'#sel_modelitem\');\r\n                        $(\'#sel_modelitem\').val(\'");

            
            #line 207 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                            Write(Model.ModelItemID);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n                    });\r\n                }\r\n            } else  if(\'");

            
            #line 210 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                   Write(Model.LinkMode);

            
            #line default
            #line hidden
WriteLiteral("\' == 3){\r\n                $(\'#div_model\').hide();\r\n                $(\'#div_link\')" +
".show();\r\n            } else if (\'");

            
            #line 213 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                   Write(Model.LinkMode);

            
            #line default
            #line hidden
WriteLiteral(@"' == 4) {
                    $('#div_model').hide();
                    $('#div_link').hide();
                    $('#div_file').show();
            }else {
                $('#div_model').hide();
            }

           $('#sel_model').change(function () {
               $('#sel_modelitem').empty();
               $.post('");

            
            #line 223 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                  Write(Url.Action("GetModelItem"));

            
            #line default
            #line hidden
WriteLiteral("\', {\r\n                   \"modelid\": $(\'#sel_model\').val(),\r\n                    \'" +
"menutype\' :\'");

            
            #line 225 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                            Write(Model.MenuType);

            
            #line default
            #line hidden
WriteLiteral("\'\r\n               }, function (data) {\r\n                     $(data).appendTo(\'#s" +
"el_modelitem\');\r\n                });\r\n            });\r\n           $(\'.LinkMode\')" +
".change(function () {\r\n               $(\'#sel_model\').val(\'\');\r\n               $" +
"(\'#sel_modelitem\').empty(\'\');\r\n               var value = $(\'input[name=LinkMode" +
"]:checked\').val();\r\n               if (value != \"2\") {\r\n                   $(\'#d" +
"iv_model\').hide();\r\n                   $(\'#div_link\').hide();\r\n                 " +
"  $(\'#div_file\').hide();\r\n                   if (value == \"3\") {\r\n              " +
"         $(\'#div_link\').show();\r\n                   }\r\n                   if (va" +
"lue == \"4\") {\r\n                       $(\'#div_file\').show();\r\n                  " +
" }\r\n               } else {\r\n                   $(\'#div_model\').show();\r\n       " +
"            $(\'#div_link\').hide();\r\n                   $(\'#div_file\').hide();\r\n " +
"              }\r\n            });\r\n\r\n            $(\'#editform\').submit(function (" +
"event) {\r\n               $(\".required\").hide();\r\n               var inputval = $" +
"(\"#editform :input\").filter(function () { return $(this).val() == \"\" && $(this)." +
"hasClass(\'checkitem\'); });\r\n                for (var idx = 0; idx < inputval.len" +
"gth; idx++) {\r\n                    $(\"#\" + inputval[idx].name + \"-error\").show()" +
";\r\n                }\r\n                if (inputval.length > 0) { return false; }" +
"\r\n                if ($(\'#sel_model\').val() != \"\" && $(\'#sel_modelitem\').val() =" +
"= \"\") {\r\n                    alert(\"請選擇程式模組\");\r\n                    return false" +
";\r\n                }\r\n                if ($(\'#div_link\').is(\':visible\') && $(\'#L" +
"inkUrl\').val() == \"\") {\r\n                    alert(\"請輸入連結\");\r\n                  " +
"  return false;\r\n                }\r\n                var file = $(\"#file_image\");" +
"\r\n                var _validFileExtensions = [\".jpg\", \".png\", \".gif\", \".jpeg\"];\r" +
"\n                var sFileName = file.val();\r\n                if (sFileName.leng" +
"th > 0) {\r\n                    var blnValid = false;\r\n                    for (v" +
"ar j = 0; j < _validFileExtensions.length; j++) {\r\n                        var s" +
"CurExtension = _validFileExtensions[j];\r\n                        if (sFileName.s" +
"ubstr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase" +
"() == sCurExtension.toLowerCase()) {\r\n                            blnValid = tru" +
"e;\r\n                            break;\r\n                        }\r\n             " +
"       }\r\n                    if (!blnValid) {\r\n                        alert(\"只" +
"能上傳Image檔案\");\r\n                        file.outerHTML = file.outerHTML;\r\n       " +
"                 return false;\r\n                    }\r\n                }\r\n      " +
"          var formData = new FormData();\r\n                var array = $(\'#editfo" +
"rm\').serializeArray();\r\n                $.each(array, function () {\r\n           " +
"         formData.append(this.name, this.value);\r\n                });\r\n\r\n       " +
"         formData.append(\'FrontDisplay\', $(\'#FrontDisplay\').prop(\'checked\') ? tr" +
"ue : false);\r\n\r\n                var images = $(\'#file_image\').get(0).files;\r\n   " +
"             if (images.length > 0) {\r\n                    formData.append(\"Imag" +
"eFile\", images[0]);\r\n                } else {\r\n                    formData.appe" +
"nd(\"ImageFile\", null);\r\n                }\r\n                var uploadfile = $(\'#" +
"uploadfile\').get(0).files;\r\n                if (uploadfile.length > 0) {\r\n      " +
"              formData.append(\"LinkUploadFile\", uploadfile[0]);\r\n               " +
" } else {\r\n                    formData.append(\"LinkUploadFile\", null);\r\n       " +
"             var value = $(\'input[name=LinkMode]:checked\').val();\r\n             " +
"       if (value == \"4\" && $(\"#LinkUploadFileName\").val()==\"\") {\r\n              " +
"          alert(\"請確實上傳檔案\");\r\n                        return false;\r\n            " +
"        }\r\n                }\r\n                formData.append(\"MenuName\", _html." +
"decode($(\'#MenuName\').val()));\r\n\r\n                formData.append(\"DeleteUploadF" +
"ile\", $(\"#DeleteUploadFile\").val());\r\n                $.ajax({\r\n                " +
"    url: this.action,\r\n                    data: formData,\r\n                    " +
"type: \'POST\',\r\n                    cache: false,\r\n                    contentTyp" +
"e: false,\r\n                    processData: false,\r\n                    success:" +
" function (data) {\r\n                        alert(data);\r\n                      " +
"  if (data.indexOf(\"成功\")>=0) { CreatePost(\'");

            
            #line 321 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                            Write(Url.Action("MainMenu"));

            
            #line default
            #line hidden
WriteLiteral("\', { menutype: \'");

            
            #line 321 "..\..\Areas\webadmin\Views\Menu\MenuEdit.cshtml"
                                                                                                   Write(Model.MenuType);

            
            #line default
            #line hidden
WriteLiteral("\'});}\r\n\r\n                    }, error: function () {\r\n                        // " +
"handle error\r\n                    }\r\n                });\r\n                return" +
" false;\r\n            });\r\n        });\r\n        </script>\r\n\r\n    ");

});

WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
