#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Oaww.Entity;
    using Oaww.Entity.SET;
    using Oaww.HtmlHelp;
    using Oaww.Utility;
    using Oaww.ViewModel;
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Lang;
    using Oaww.ViewModel.Search;
    using Oaww.ViewModel.SiteMap;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/EPaper/Subscriber.cshtml")]
    public partial class _Areas_webadmin_Views_EPaper_Subscriber_cshtml : System.Web.Mvc.WebViewPage<MessageSearchModel>
    {
        public _Areas_webadmin_Views_EPaper_Subscriber_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
  
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";
    SET_EPAPER SET_EPAPER = (SET_EPAPER)ViewBag.SET_EPAPER;
    var LangID =  ViewBag.LangID;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 199), Tuple.Create("\"", 243)
            
            #line 7 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
, Tuple.Create(Tuple.Create("", 205), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/datatable.js")
            
            #line default
            #line hidden
, 205), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 263), Tuple.Create("\"", 304)
            
            #line 8 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
, Tuple.Create(Tuple.Create("", 269), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/custom.js")
            
            #line default
            #line hidden
, 269), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 324), Tuple.Create("\"", 391)
            
            #line 9 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
, Tuple.Create(Tuple.Create("", 330), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/components-date-time-pickers.min.js")
            
            #line default
            #line hidden
, 330), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 411), Tuple.Create("\"", 470)
            
            #line 10 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
, Tuple.Create(Tuple.Create("", 417), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/bootstrap-datepicker.min.js")
            
            #line default
            #line hidden
, 417), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 490), Tuple.Create("\"", 536)
            
            #line 11 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
, Tuple.Create(Tuple.Create("", 496), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/bootbox.min.js")
            
            #line default
            #line hidden
, 496), false)
);

WriteLiteral("></script>\r\n<!--page bar start-->\r\n<div");

WriteLiteral(" class=\"page-bar\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 658), Tuple.Create("\"", 692)
            
            #line 16 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
, Tuple.Create(Tuple.Create("", 665), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 665), false)
);

WriteLiteral(">Home</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            模組元件\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            電子報管理\r\n        </li>\r\n    </ul>\r\n" +
"</div>\r\n<!--page bar end-->\r\n<!--message start-->\r\n<h2>電子報管理</h2>\r\n\r\n<div");

WriteLiteral(" class=\"portlet light bordered\"");

WriteLiteral(">\r\n\r\n    <!--management item start-->\r\n    <div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" class=\"class_title\"");

WriteLiteral(">管理項目</p>\r\n                <select");

WriteLiteral(" class=\"form-control_1\"");

WriteLiteral(" onChange=\"window.location.href=this.value\"");

WriteLiteral(">\r\n                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1348), Tuple.Create("\"", 1412)
            
            #line 40 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
, Tuple.Create(Tuple.Create("", 1356), Tuple.Create<System.Object, System.Int32>(Url.Action("ModelItem",new { mainid = ViewBag.mainid })
            
            #line default
            #line hidden
, 1356), false)
);

WriteLiteral(">編輯管理</option>\r\n                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1456), Tuple.Create("\"", 1522)
            
            #line 41 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
, Tuple.Create(Tuple.Create("", 1464), Tuple.Create<System.Object, System.Int32>(Url.Action("UnitSetting",new { mainid = ViewBag.mainid })
            
            #line default
            #line hidden
, 1464), false)
);

WriteLiteral(">模組設定</option>\r\n                    <option");

WriteLiteral(" value=\"#\"");

WriteLiteral(" selected>訂閱者管理</option>\r\n                </select>\r\n            </div>\r\n        " +
"</div>\r\n    </div>\r\n    <hr>\r\n    <!--management item end-->\r\n    <!--set item s" +
"tart-->\r\n    <div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 col-sm-12 col-xs-12 mobile_left\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn blue search_icon\"");

WriteLiteral(">搜尋 <i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i></button>\r\n                <button");

WriteLiteral(" class=\"btn green-meadow epaper_sub\"");

WriteLiteral(" id=\"btn_add\"");

WriteLiteral(">新增 <i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i></button>\r\n                <button");

WriteLiteral(" class=\"btn grey-cascade\"");

WriteLiteral(" id=\'btn_export\'");

WriteLiteral(">匯出</button>\r\n            </p>\r\n        </div>\r\n    </div>\r\n    <!--set item end-" +
"->\r\n    <!--search item start-->\r\n    <div");

WriteLiteral(" class=\"search_menu\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 search_item_1\"");

WriteLiteral(">訂閱/取消日期</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 bg-white\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"input-group input-large date-picker input-daterange\"");

WriteLiteral(" data-date=\"10/11/2012\"");

WriteLiteral(" data-date-format=\"yyyy/mm/dd\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"from\"");

WriteLiteral(" placeholder=\"開始日期\"");

WriteLiteral(" id=\"txt_OPDateFrom\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("> to </span>\r\n                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"to\"");

WriteLiteral(" placeholder=\"結束日期\"");

WriteLiteral(" id=\"txt_OPDateTo\"");

WriteLiteral(">\r\n                                </div>\r\n                            </div>\r\n  " +
"                      </div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 search_item_1\"");

WriteLiteral(">Email</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 bg-white\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"txt_EMail\"");

WriteLiteral(">\r\n                            </div>\r\n                        </div>\r\n          " +
"              <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 search_item_1\"");

WriteLiteral(">訂閱狀況</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 bg-white\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" class=\"form-control w-auto\"");

WriteLiteral(" id=\"sel_Status\"");

WriteLiteral(">\r\n                                    <option selected");

WriteLiteral(" value=\"\"");

WriteLiteral(">全部</option>\r\n                                    <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">已訂閱</option>\r\n                                    <option");

WriteLiteral(" value=\"0\"");

WriteLiteral(">取消訂閱</option>\r\n                                </select>\r\n                      " +
"      </div>\r\n                        </div>\r\n\r\n                    </div>\r\n    " +
"            </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"text-center search_padding\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_search\"");

WriteLiteral(">搜尋 <i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i></button>\r\n        </div>\r\n    </div>\r\n    <!--search item end-->\r\n    <!--t" +
"able start-->\r\n    <div");

WriteLiteral(" class=\"table-scrollable\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table table-bordered table-hover\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral("\r\n               id=\"eventtable\"");

WriteLiteral("\r\n               data-url=\"");

            
            #line 106 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
                    Write(Url.Action("PagingEpaperOrder"));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n               data-sort-name=\'UpdateDate\'");

WriteLiteral("\r\n               data-page-size=\'10\'");

WriteLiteral("\r\n               data-filed-id=\'ID\'");

WriteLiteral("\r\n               data-max-pagination=\'10\'");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th");

WriteLiteral(" width=\"80\"");

WriteLiteral(" class=\"text-center delete_th\"");

WriteLiteral(" filed-type=\'delcheckbox\'");

WriteLiteral(">\r\n                        <label");

WriteLiteral(" class=\'mt-checkbox mt-checkbox-single mt-checkbox-outline\'");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\'checkbox\'");

WriteLiteral(" class=\'checkboxes\'");

WriteLiteral(" id=\"chk_all\"");

WriteLiteral(" /><span></span>\r\n                        </label>\r\n                        <butt" +
"on");

WriteLiteral(" class=\"btn red-mint btn-xs\"");

WriteLiteral(" id=\'btn_del\'");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-trash\"");

WriteLiteral("></i></button>\r\n                    </th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" filed-name=\'OPDateStr\'");

WriteLiteral(" filed-item-class=\'text-center\'");

WriteLiteral(">訂閱／取消日期</th>\r\n                    <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" style=\"min-width:100px\"");

WriteLiteral(" filed-name=\'EMail\'");

WriteLiteral(" filed-item-class=\'text-center\'");

WriteLiteral(">Email</th>\r\n                    <th");

WriteLiteral(" filed-name=\'Status\'");

WriteLiteral(" width=\"80px\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" filed-type=\'checkbox\'");

WriteLiteral(" filed-item-class=\"checkboxes chkstatus\"");

WriteLiteral(">是否訂閱</th>\r\n                </tr>\r\n            </thead>\r\n            <tbody></tbo" +
"dy>\r\n        </table>\r\n    </div>\r\n    <!--table end-->\r\n    <!--頁碼 start-->\r\n  " +
"  <div");

WriteLiteral(" id=\"page_number\"");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-4 col-sm-12 col-xs-12 page_total\"");

WriteLiteral(" id=\"tableinfo\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"col-md-8 col-sm-12 col-xs-12 page_icon\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(" id=\"pagination\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <!--頁碼 end-->\r\n\r\n\r\n</div>\r" +
"\n<!--message end-->\r\n<!--message end-->\r\n");

DefineSection("scripts", () => {

WriteLiteral(@"
    <script>
        $(document).ready(function () {
            
            RegisterSearchItem();
        mytable = $(""#eventtable"").myDataTable().TableList[0];
        mytable.settingTdData = myDataTableTr;
        mytable.settingTableInfo = function (tableinfoId, totalcnt, offsetcnt, nowpagecnt) {
            var totalclick = mytable.keepcheckid.length;
            $(""#"" + tableinfoId).html('總筆數:' + totalcnt + '，顯示' + (totalcnt <= 0 ? 0 : offsetcnt) + ""~"" + (offsetcnt + nowpagecnt - 1));
            };

        mytable.SearchModelBase.Key = ""0"";
        mytable.SearchModelBase.OrderEPaper = ""1"";
        mytable.GetData(1);
        $(""#btn_add"").click(function () { CallAddDialog('");

            
            #line 157 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
                                                    Write(Url.Action("AddSubscriber"));

            
            #line default
            #line hidden
WriteLiteral("\', { sid: -1, item: \"E-Mail\", title: \"請輸入訂閱者Mail\" }); });\r\n         RegisterClick" +
"All(\"#chk_all\", \'#eventtable tbody .chksel\', \"#selvalue\");\r\n         RegisterDel" +
"ete(\"#btn_del\", \'#eventtable .chksel:checked\', \'");

            
            #line 159 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
                                                               Write(Url.Action("DelSubscriber"));

            
            #line default
            #line hidden
WriteLiteral("\', {});\r\n         RegisterClick(\"#eventtable\", \".chkstatus\", \'");

            
            #line 160 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
                                                Write(Url.Action("SetSubscriberStatus"));

            
            #line default
            #line hidden
WriteLiteral(@"', {});
         $(""#btn_search"").click(function () {
                var SearchModelBase = mytable.SearchModelBase;
                SearchModelBase.DateTo = $('#txt_OPDateTo').val();
                SearchModelBase.DateFrom = $('#txt_OPDateFrom').val();
                SearchModelBase.EMail = $('#txt_EMail').val();
                SearchModelBase.Status = $('#sel_Status' ).val();
                SearchModelBase.Search = ""Y"";
                SearchModelBase.LangID = ");

            
            #line 168 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
                                    Write(LangID);

            
            #line default
            #line hidden
WriteLiteral(@";
                mytable.GetData();
            });

            $(""#btn_export"").click(function () {
                var SearchModelBase = mytable.SearchModelBase;
                SearchModelBase.DateTo = $('#txt_OPDateTo').val();
                SearchModelBase.DateFrom = $('#txt_OPDateFrom').val();
                SearchModelBase.EMail = $('#txt_EMail').val();
                SearchModelBase.Status = $('#sel_Status').val();
                SearchModelBase.Search = ""Y"";
                SearchModelBase.LangID = ");

            
            #line 179 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
                                    Write(LangID);

            
            #line default
            #line hidden
WriteLiteral(";\r\n                CreatePost(\'");

            
            #line 180 "..\..\Areas\webadmin\Views\EPaper\Subscriber.cshtml"
                       Write(Url.Action("Export"));

            
            #line default
            #line hidden
WriteLiteral("\', SearchModelBase);\r\n            });\r\n    });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
