#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Oaww.Entity;
    using Oaww.Entity.SET;
    using Oaww.HtmlHelp;
    using Oaww.Utility;
    
    #line 1 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
    using Oaww.ViewModel;
    
    #line default
    #line hidden
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Lang;
    using Oaww.ViewModel.Search;
    using Oaww.ViewModel.SiteMap;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/EPaper/UnitSetting.cshtml")]
    public partial class _Areas_webadmin_Views_EPaper_UnitSetting_cshtml : System.Web.Mvc.WebViewPage<EPaperUnitSettingModel>
    {
        public _Areas_webadmin_Views_EPaper_UnitSetting_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
   
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";
    SET_EPAPER SET_EPAPER = (SET_EPAPER)ViewBag.SET_EPAPER;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("<script");

WriteAttribute("src", Tuple.Create(" src=\"", 197), Tuple.Create("\"", 264)
            
            #line 9 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
, Tuple.Create(Tuple.Create("", 203), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/components-date-time-pickers.min.js")
            
            #line default
            #line hidden
, 203), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 284), Tuple.Create("\"", 343)
            
            #line 10 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
, Tuple.Create(Tuple.Create("", 290), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/bootstrap-datepicker.min.js")
            
            #line default
            #line hidden
, 290), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 363), Tuple.Create("\"", 404)
            
            #line 11 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
, Tuple.Create(Tuple.Create("", 369), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/custom.js")
            
            #line default
            #line hidden
, 369), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 424), Tuple.Create("\"", 476)
            
            #line 12 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
, Tuple.Create(Tuple.Create("", 430), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ckeditor/ckeditor.js")
            
            #line default
            #line hidden
, 430), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 496), Tuple.Create("\"", 542)
            
            #line 13 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
, Tuple.Create(Tuple.Create("", 502), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/bootbox.min.js")
            
            #line default
            #line hidden
, 502), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("\r\n<!-- 載入 summernote 中文語系 -->\r\n<!--page bar start-->\r\n<div");

WriteLiteral(" class=\"page-bar\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 765), Tuple.Create("\"", 799)
            
            #line 20 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
, Tuple.Create(Tuple.Create("", 772), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 772), false)
);

WriteLiteral(">Home</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            模組元件\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            電子報管理\r\n        </li>\r\n    </ul>\r\n" +
"\r\n</div>\r\n<!--page bar end-->\r\n<!--message start-->\r\n<h2>電子報管理</h2>\r\n\r\n<div");

WriteLiteral(" class=\"portlet light bordered\"");

WriteLiteral(">\r\n\r\n    <!--management item start-->\r\n    <div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-12 col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" class=\"class_title\"");

WriteLiteral(">管理項目</p>\r\n                <select");

WriteLiteral(" class=\"form-control_1\"");

WriteLiteral(" onChange=\"window.location.href=this.value\"");

WriteLiteral(">\r\n                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1457), Tuple.Create("\"", 1485)
            
            #line 45 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
, Tuple.Create(Tuple.Create("", 1465), Tuple.Create<System.Object, System.Int32>(Url.Action("Index")
            
            #line default
            #line hidden
, 1465), false)
);

WriteLiteral(">編輯管理</option>\r\n                    <option");

WriteLiteral(" value=\"#\"");

WriteLiteral(" selected>模組設定</option>\r\n                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1591), Tuple.Create("\"", 1624)
            
            #line 47 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
, Tuple.Create(Tuple.Create("", 1599), Tuple.Create<System.Object, System.Int32>(Url.Action("Subscriber")
            
            #line default
            #line hidden
, 1599), false)
);

WriteLiteral(">訂閱者管理</option>\r\n                </select>\r\n            </div>\r\n        </div>\r\n " +
"   </div>\r\n    <!--<hr>-->\r\n    <!--management item end-->\r\n    <form");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral(" id=\"editform\"");

WriteAttribute("action", Tuple.Create(" action=\'", 1841), Tuple.Create("\'", 1873)
            
            #line 54 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
    , Tuple.Create(Tuple.Create("", 1850), Tuple.Create<System.Object, System.Int32>(Url.Action("SaveUnit")
            
            #line default
            #line hidden
, 1850), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 55 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
   Write(Html.HiddenFor(Model => Model.ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 56 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 62 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                   Write(Html.HiddenFor(Model => Model.MainID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 63 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                   Write(Html.HiddenFor(Model => Model.ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral(">列表顯示設定列表</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <!--table start-->\r\n                          " +
"      <table");

WriteLiteral(" class=\"table table-bordered nomarginbottom\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(" id=\"table_Column\"");

WriteLiteral(">\r\n                                    <thead>\r\n                                 " +
"       <tr>\r\n                                            <th");

WriteLiteral(" width=\"120\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">排序</th>\r\n                                            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">欄位名稱</th>\r\n                                            <th");

WriteLiteral(" width=\"60\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">顯示</th>\r\n                                        </tr>\r\n                        " +
"            </thead>\r\n                                    <tbody>\r\n");

            
            #line 77 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 77 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                          
                                            for (var idx = 0; idx < Model.columnSettings.Count(); idx++)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <tr");

WriteLiteral(" class=\"odd gradeX tr_col\"");

WriteAttribute("id", Tuple.Create(" id=\"", 3467), Tuple.Create("\"", 3479)
, Tuple.Create(Tuple.Create("", 3472), Tuple.Create("tr_", 3472), true)
            
            #line 80 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
     , Tuple.Create(Tuple.Create("", 3475), Tuple.Create<System.Object, System.Int32>(idx
            
            #line default
            #line hidden
, 3475), false)
);

WriteAttribute("seqidx", Tuple.Create(" seqidx=\"", 3480), Tuple.Create("\"", 3497)
            
            #line 80 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                    , Tuple.Create(Tuple.Create("", 3489), Tuple.Create<System.Object, System.Int32>(idx+1
            
            #line default
            #line hidden
, 3489), false)
);

WriteLiteral(">\r\n                                                    <td");

WriteLiteral(" class=\"text-center delete_th\"");

WriteLiteral(">\r\n                                                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default btn-xs seq_list\"");

WriteLiteral(" value=\"0\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-angle-double-up\"");

WriteLiteral("></i></button>\r\n                                                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default btn-xs seq_list\"");

WriteLiteral(" value=\"-1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-angle-up\"");

WriteLiteral("></i></button>\r\n                                                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default btn-xs seq_list\"");

WriteLiteral(" value=\"+1\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-angle-down\"");

WriteLiteral("></i></button>\r\n                                                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default btn-xs seq_list\"");

WriteLiteral(" value=\"max\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-angle-double-down\"");

WriteLiteral("></i></button>\r\n                                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"Type\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4373), Tuple.Create("\"", 4412)
            
            #line 86 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
              , Tuple.Create(Tuple.Create("", 4381), Tuple.Create<System.Object, System.Int32>(Model.columnSettings[idx].Type
            
            #line default
            #line hidden
, 4381), false)
);

WriteLiteral(" />\r\n                                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"MainID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4506), Tuple.Create("\"", 4547)
            
            #line 87 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                , Tuple.Create(Tuple.Create("", 4514), Tuple.Create<System.Object, System.Int32>(Model.columnSettings[idx].MainID
            
            #line default
            #line hidden
, 4514), false)
);

WriteLiteral(" />\r\n                                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ColumnKey\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4644), Tuple.Create("\"", 4688)
            
            #line 88 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                   , Tuple.Create(Tuple.Create("", 4652), Tuple.Create<System.Object, System.Int32>(Model.columnSettings[idx].ColumnKey
            
            #line default
            #line hidden
, 4652), false)
);

WriteLiteral(" />\r\n                                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ColumnName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4786), Tuple.Create("\"", 4831)
            
            #line 89 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                    , Tuple.Create(Tuple.Create("", 4794), Tuple.Create<System.Object, System.Int32>(Model.columnSettings[idx].ColumnName
            
            #line default
            #line hidden
, 4794), false)
);

WriteLiteral(" />\r\n                                                    </td>\r\n                 " +
"                                   <td");

WriteLiteral(" class=\"text-center columnname\"");

WriteLiteral(">");

            
            #line 91 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                                                                  Write(Model.columnSettings[idx].ColumnName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                                    <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" class=\"mt-checkbox mt-checkbox-single mt-checkbox-outline\"");

WriteLiteral(">\r\n                                                            <input");

WriteLiteral(" class=\"chkstatus\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" ");

            
            #line 94 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                                                                                 Write(Model.columnSettings[idx].Used == true ? "checked='checked'" : "");

            
            #line default
            #line hidden
WriteLiteral("><span></span>\r\n                                                        </label>\r" +
"\n                                                    </td>\r\n                    " +
"                            </tr>\r\n");

            
            #line 98 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                            }
                                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </tbody>\r\n                                <" +
"/table>\r\n                                <!--table end-->\r\n                     " +
"       </div>\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral("><span");

WriteLiteral(" class=\"red\"");

WriteLiteral(">*</span> 每頁顯示筆數</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" class=\"form_02\"");

WriteLiteral(" id=\"ShowCount\"");

WriteLiteral(" name=\"ShowCount\"");

WriteLiteral(">\r\n\r\n");

            
            #line 111 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 111 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                     foreach (var m in SET_EPAPER.M_EPAPER13.Split(','))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <option");

WriteAttribute("value", Tuple.Create(" value=\"", 6408), Tuple.Create("\"", 6418)
            
            #line 113 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
, Tuple.Create(Tuple.Create("", 6416), Tuple.Create<System.Object, System.Int32>(m
            
            #line default
            #line hidden
, 6416), false)
);

WriteLiteral(">");

            
            #line 113 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                                      Write(m);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 114 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n  " +
"                      </div>\r\n                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 6611), Tuple.Create("\"", 6671)
, Tuple.Create(Tuple.Create("", 6619), Tuple.Create("form-group", 6619), true)
            
            #line 118 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
, Tuple.Create(Tuple.Create(" ", 6629), Tuple.Create<System.Object, System.Int32>(SET_EPAPER.M_EPAPER17==false?"hide":""
            
            #line default
            #line hidden
, 6630), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-2 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">簡介</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-10 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <textarea");

WriteLiteral(" cols=\"80\"");

WriteLiteral(" id=\"IntroductionHtml\"");

WriteLiteral(" rows=\"20\"");

WriteLiteral(">");

            
            #line 121 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                                                               Write(HttpUtility.HtmlDecode(Model.IntroductionHtml));

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                            </div>\r\n                        </div>\r\n" +
"                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral("><span");

WriteLiteral(" class=\"red\"");

WriteLiteral(">*</span> 表格摘要</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <textarea");

WriteLiteral(" cols=\"80\"");

WriteLiteral(" id=\"Summary\"");

WriteLiteral(" rows=\"3\"");

WriteLiteral(" name=\"Summary\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" maxlength=\"500\"");

WriteLiteral(">");

            
            #line 127 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                                                                                                         Write(Model.Summary);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                            </div>\r\n                        </div>\r\n" +
"\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral(">基本語系設定</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white\"");

WriteLiteral(">\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">序號</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 138 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column1, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">發佈日期</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 145 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column2, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">電子報名稱</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 152 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column3, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">年份</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 159 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column4, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">電子報訂閱</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 166 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column5, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">訂閱</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 173 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column6, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">取消訂閱</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 180 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column7, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">查閱電子報</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 187 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column8, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">Email</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 194 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column9, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">Email 格式有誤</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 201 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column10, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">此 Email 已有訂閱電子報!</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 208 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column11, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">電子報訂閱成功!</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 215 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column12, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">此 Email 無訂閱電子報!</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 222 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column13, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">電子報取消訂閱成功!</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 229 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Html.EditorFor(model => model.Column14, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral(@"
                                    </div>
                                </div>


                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div");

WriteLiteral(" class=\"text-center search_padding\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(">確認送出</button>\r\n        </div>\r\n    </form>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script>\r\n        $(function () {\r\n            $(\"#ShowCount\").val(\'");

            
            #line 250 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                            Write(Model.ShowCount);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n            $(\"#table_Column\").delegate((\".seq_list\"), \"click\", function () " +
"{\r\n                var alltr = $(\"#table_Column tbody tr\");\r\n                var" +
" nowtridx = $(this).parents(\'tr\').attr(\'seqidx\');\r\n                var sval = $(" +
"this).val();\r\n                var newtridx = 0;\r\n\r\n                if (sval == \"" +
"+1\") {\r\n                    newtridx = parseInt(nowtridx) + 1;\r\n                " +
"} else if (sval == \"-1\") {\r\n                    newtridx = parseInt(nowtridx) - " +
"1;\r\n                } else if (sval == \"max\") {\r\n                    newtridx = " +
"alltr.length;\r\n                }\r\n                if (newtridx == \"0\") { newtrid" +
"x = \"1\"; }\r\n                if (newtridx == \"\" || newtridx == nowtridx) {\r\n     " +
"               return false;\r\n                }\r\n                if (newtridx > " +
"alltr.length) { newtridx = alltr.length; }\r\n                if (nowtridx == newt" +
"ridx.toString()) {\r\n                    return false;\r\n                }\r\n\r\n    " +
"            var nowidxhtml = $(this).parents(\'tr\')[0];\r\n                var adda" +
"rr = [];\r\n                for (var idx = 1; idx <= alltr.length; idx++) {\r\n     " +
"               var nowtr = alltr[idx - 1];\r\n                    if (idx.toString" +
"() != nowtridx) {\r\n                        if ((newtridx > nowtridx)) {\r\n       " +
"                     addarr.push($(nowtr));\r\n                            if (idx" +
" == newtridx) {\r\n                                addarr.push($(nowidxhtml));\r\n  " +
"                          }\r\n                        } else {\r\n                 " +
"           if (idx == newtridx) {\r\n                                addarr.push($" +
"(nowidxhtml));\r\n                            }\r\n                            addar" +
"r.push($(nowtr));\r\n                        }\r\n                    }\r\n           " +
"     }\r\n                $(\"#table_Column tbody\").empty();\r\n\r\n                for" +
" (var idx = 0; idx < addarr.length; idx++) {\r\n                    $(addarr[idx])" +
".attr(\"id\", \"tr_\" + idx).attr(\'seqidx\', (idx + 1));\r\n                    $(\"#tab" +
"le_Column tbody\").append(addarr[idx]);\r\n                }\r\n            });\r\n    " +
"        $(\'#editform\').submit(function (event) {\r\n                var formData =" +
" new FormData();\r\n                var array = $(\'#editform\').serializeArray();\r\n" +
"                $.each(array, function () {\r\n                    formData.append" +
"(this.name, this.value);\r\n                });\r\n\r\n                var i = 0;\r\n   " +
"             $(\'.tr_col\').each(function () {\r\n                    formData.appen" +
"d(\"columnSettings[\" + i + \"].Type\", $(this).find(\'#Type\').val());\r\n             " +
"       formData.append(\"columnSettings[\" + i + \"].MainID\", $(this).find(\'#MainID" +
"\').val());\r\n                    formData.append(\"columnSettings[\" + i + \"].Colum" +
"nKey\", $(this).find(\'#ColumnKey\').val());\r\n                    formData.append(\"" +
"columnSettings[\" + i + \"].ColumnName\", $(this).find(\'#ColumnName\').val());\r\n    " +
"                formData.append(\"columnSettings[\" + i + \"].Used\", $(this).find(\'" +
"#Used\').prop(\'checked\') ? true : false);\r\n                    formData.append(\"c" +
"olumnSettings[\" + i + \"].Sort\", i + 1);\r\n\r\n                    i++;\r\n           " +
"     })\r\n                formData.append(\"Summary\", encodeURIComponent($(\'#Summa" +
"ry\').val()));\r\n                formData.append(\"IntroductionHtml\", _html.encode(" +
"CKEDITOR.instances.IntroductionHtml.getData()));\r\n                $.ajax({\r\n    " +
"                url: this.action,\r\n                    data: formData,\r\n        " +
"            type: \'POST\',\r\n                    cache: false,\r\n                  " +
"  contentType: false,\r\n                    processData: false,\r\n                " +
"    success: function (data) {\r\n                        if (data == \"\") {\r\n     " +
"                       alert(\"儲存成功\");\r\n                        } else {\r\n       " +
"                     alert(data);\r\n                            var obj = {};\r\n  " +
"                              obj.mainid = \'");

            
            #line 331 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                         Write(Model.MainID);

            
            #line default
            #line hidden
WriteLiteral("\'\r\n                            CreatePost(\'");

            
            #line 332 "..\..\Areas\webadmin\Views\EPaper\UnitSetting.cshtml"
                                   Write(Url.Action("UnitSetting"));

            
            #line default
            #line hidden
WriteLiteral("\', obj);\r\n                        }\r\n                    }, error: function () {\r" +
"\n                        // handle error\r\n                    }\r\n               " +
" });\r\n                return false;\r\n            });\r\n        });\r\n    </script>" +
"\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
