#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Oaww.Entity;
    using Oaww.Entity.SET;
    using Oaww.HtmlHelp;
    using Oaww.Utility;
    
    #line 1 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
    using Oaww.ViewModel;
    
    #line default
    #line hidden
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Lang;
    using Oaww.ViewModel.Search;
    using Oaww.ViewModel.SiteMap;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/Site/PrintSetting.cshtml")]
    public partial class _Areas_webadmin_Views_Site_PrintSetting_cshtml : System.Web.Mvc.WebViewPage<SiteLayoutModel>
    {
        public _Areas_webadmin_Views_Site_PrintSetting_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
  
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--page bar start-->\r\n<div");

WriteLiteral(" class=\"page-bar all_width\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 236), Tuple.Create("\"", 270)
            
            #line 10 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
, Tuple.Create(Tuple.Create("", 243), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 243), false)
);

WriteLiteral(">Home</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <span");

WriteLiteral(" href=\"#\"");

WriteLiteral(">版面設定</span>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <span");

WriteLiteral(" href=\"#\"");

WriteLiteral(">網站版面資訊設定</span>\r\n        </li>\r\n    </ul>\r\n</div>\r\n<!--page bar end-->\r\n<!--mess" +
"age start-->\r\n<div");

WriteLiteral(" class=\"title_01\"");

WriteLiteral(">網站版面資訊設定</div>\r\n\r\n<div");

WriteLiteral(" class=\"portlet light bordered\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"table-toolbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-6 col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"class_title\"");

WriteLiteral(">管理項目</p>\r\n            <div");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"form-control_1\"");

WriteLiteral(" id=\"sel_unit\"");

WriteLiteral(">\r\n                    <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">網站版面</option>\r\n                    <option");

WriteLiteral(" value=\"2\"");

WriteLiteral(">轉寄好友</option>\r\n                    <option");

WriteLiteral(" value=\"3\"");

WriteLiteral(" selected=\"selected\"");

WriteLiteral(">友善列印</option>\r\n                    <option");

WriteLiteral(" value=\"4\"");

WriteLiteral(">無法顯示頁面</option>\r\n                   \r\n                </select>\r\n            </d" +
"iv>\r\n        </div>\r\n    </div>\r\n\r\n    <form");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral(" id=\"editform\"");

WriteAttribute("action", Tuple.Create(" action=\'", 1307), Tuple.Create("\'", 1350)
            
            #line 43 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
    , Tuple.Create(Tuple.Create("", 1316), Tuple.Create<System.Object, System.Int32>(Url.Action("SavePrintSiteLayout")
            
            #line default
            #line hidden
, 1316), false)
);

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 44 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
   Write(Html.HiddenFor(Model => Model.ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 45 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
   Write(Html.HiddenFor(Model => Model.PrintImgNameOri));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 46 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
   Write(Html.HiddenFor(Model => Model.PrintImgShowName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 47 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
   Write(Html.HiddenFor(Model => Model.SType));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(" id=\"form-body2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral(">風格圖片</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" id=\"div_oldprintfile\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2216), Tuple.Create("\"", 2299)
            
            #line 57 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
, Tuple.Create(Tuple.Create("", 2223), Tuple.Create<System.Object, System.Int32>(Model.PrintImageUrl.IsNullOrEmpty()  ?"":Url.Content(Model.PrintImageUrl)
            
            #line default
            #line hidden
, 2223), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(">");

            
            #line 57 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
                                                                                                                                           Write(Model.PrintImgShowName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        <label");

WriteLiteral(" style=\"color:blue;margin-left:10px;cursor:pointer\"");

WriteLiteral(" id=\"delprintimage\"");

WriteLiteral(">刪除</label>\r\n                                    </div>\r\n                        " +
"            <div");

WriteLiteral(" style=\"display:inline\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"exampleInputFile\"");

WriteLiteral(" class=\"control-label display_inline\"");

WriteLiteral(">圖片上傳</label>\r\n                                        <input");

WriteLiteral(" id=\"file_printimage\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(" name=\"FirstpageImageFile\"");

WriteLiteral(" accept=\"image/*\"");

WriteLiteral(" />\r\n                                        <div");

WriteLiteral(" class=\"required\"");

WriteLiteral(">建議尺寸 740*185 px，限jpg、gif、png格式</div>\r\n                                    </div>" +
"\r\n                                </div>\r\n                            </div>\r\n  " +
"                      </div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-2 col-xs-12 search_item\"");

WriteLiteral(">網站資訊</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-10 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <textarea");

WriteLiteral(" cols=\"80\"");

WriteLiteral(" id=\"PrintHtmlContent\"");

WriteLiteral(" rows=\"20\"");

WriteLiteral(">");

            
            #line 71 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
                                                                               Write(HttpUtility.HtmlDecode(Model.PrintHtmlContent));

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                            </div>\r\n                        </div>\r\n" +
"                    </div>\r\n                </div>\r\n            </div>\r\n        " +
"</div>\r\n        <div");

WriteLiteral(" class=\"text-center search_padding\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(">確認送出</button>\r\n        </div>\r\n    </form>\r\n\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3849), Tuple.Create("\"", 3916)
            
            #line 85 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
, Tuple.Create(Tuple.Create("", 3855), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/components-date-time-pickers.min.js")
            
            #line default
            #line hidden
, 3855), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3940), Tuple.Create("\"", 3995)
            
            #line 86 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
, Tuple.Create(Tuple.Create("", 3946), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/bootstrap-datepicker.js")
            
            #line default
            #line hidden
, 3946), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4019), Tuple.Create("\"", 4071)
            
            #line 87 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
, Tuple.Create(Tuple.Create("", 4025), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ckeditor/ckeditor.js")
            
            #line default
            #line hidden
, 4025), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4095), Tuple.Create("\"", 4136)
            
            #line 88 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
, Tuple.Create(Tuple.Create("", 4101), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/custom.js")
            
            #line default
            #line hidden
, 4101), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4160), Tuple.Create("\"", 4184)
, Tuple.Create(Tuple.Create("", 4166), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/_html.js")
, 4166), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n\r\n           if (\'");

            
            #line 93 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
           Write(Model.ID);

            
            #line default
            #line hidden
WriteLiteral("\'>0 && \'");

            
            #line 93 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
                            Write(Model.PrintImgNameOri);

            
            #line default
            #line hidden
WriteLiteral(@"'!='') {
               $('#div_oldprintfile').show();
            }
           $('#delprintimage').click(function () {
               $('#div_oldprintfile').hide();
               $('#PrintImgNameOri').val('');
               $('#PrintImgShowName').val('');
           });
           $(""#sel_unit"").change(function () {
                if ($(""#sel_unit"").val() == ""1"") {
                    CreatePost('");

            
            #line 103 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
                           Write(Url.Action("SiteLayout"));

            
            #line default
            #line hidden
WriteLiteral("\', { stype: $(\"#SType\").val() });\r\n                }else if ($(\"#sel_unit\").val()" +
" == \"2\") {\r\n                    CreatePost(\'");

            
            #line 105 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
                           Write(Url.Action("FowardSetting"));

            
            #line default
            #line hidden
WriteLiteral("\', { stype: $(\"#SType\").val() });\r\n                }else if ($(\"#sel_unit\").val()" +
" == \"4\") {\r\n                    CreatePost(\'");

            
            #line 107 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
                           Write(Url.Action("Page404Setting"));

            
            #line default
            #line hidden
WriteLiteral("\', { stype: $(\"#SType\").val() });\r\n                }\r\n\r\n            });\r\n        " +
"   var ckedit = CKEDITOR.replace(\'PrintHtmlContent\', {\r\n                height: " +
"300,\r\n                filebrowserImageUploadUrl: \'");

            
            #line 113 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
                                       Write(Url.Action("Upload"));

            
            #line default
            #line hidden
WriteLiteral("?command=QuickUpload&type=Images\'\r\n           });\r\n\r\n            CKEDITOR.config." +
"enterMode = CKEDITOR.ENTER_BR;\r\n            CKEDITOR.config.shiftEnterMode = CKE" +
"DITOR.ENTER_P;\r\n            CKEDITOR.on(\'instanceReady\', function (ev) {\r\n      " +
"          ev.editor.dataProcessor.writer.setRules(\'p\',\r\n                    {\r\n " +
"                       indent: false,\r\n                        breakBeforeOpen: " +
"false,\r\n                        breakAfterOpen: false,\r\n                        " +
"breakBeforeClose: false,\r\n                        breakAfterClose: false\r\n      " +
"              });\r\n            });\r\n           $(\'#editform\').submit(function (e" +
"vent) {\r\n               $(\".required\").hide();\r\n\r\n               var file = $(\"#" +
"file_printimage\");\r\n                var _validFileExtensions= [\".jpg\", \".png\", \"" +
".gif\", \".jpeg\"];\r\n                var sFileName = file.val();\r\n                i" +
"f (sFileName.length > 0) {\r\n                    var blnValid = false;\r\n         " +
"           for (var j = 0; j < _validFileExtensions.length; j++) {\r\n            " +
"            var sCurExtension = _validFileExtensions[j];\r\n                      " +
"  if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.le" +
"ngth).toLowerCase() == sCurExtension.toLowerCase()) {\r\n                         " +
"   blnValid = true;\r\n                            break;\r\n                       " +
" }\r\n                    }\r\n                    if (!blnValid) {\r\n               " +
"         alert(\"風格圖片只能上傳Image檔案\");\r\n                        file.outerHTML = fil" +
"e.outerHTML;\r\n                        return false;\r\n                    }\r\n    " +
"            }\r\n\r\n\r\n                var formData = new FormData();\r\n             " +
"   var array = $(\'#editform\').serializeArray();\r\n               formData.append(" +
"\"PrintHtmlContent\", _html.encode(CKEDITOR.instances.PrintHtmlContent.getData()))" +
";\r\n                $.each(array, function () {\r\n                    formData.app" +
"end(this.name, this.value);\r\n                });\r\n                var images = $" +
"(\'#file_printimage\').get(0).files;\r\n                if (images.length > 0) {\r\n  " +
"                  formData.append(\"PrintImageFile\", images[0]);\r\n               " +
" } else {\r\n                    formData.append(\"PrintImageFile\", null);\r\n       " +
"         }\r\n                $.ajax({\r\n                    url: this.action,\r\n   " +
"                 data: formData,\r\n                    type: \'POST\',\r\n           " +
"         cache: false,\r\n                     headers: {\r\n                       " +
" RequestVerificationToken: \'");

            
            #line 169 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
                                              Write(CommonRazorFunctions.GetAntiForgery());

            
            #line default
            #line hidden
WriteLiteral("\'\r\n                    },\r\n                    contentType: false,\r\n             " +
"       processData: false,\r\n                    success: function (data) {\r\n    " +
"                    alert(data);\r\n                        CreatePost(\'");

            
            #line 175 "..\..\Areas\webadmin\Views\Site\PrintSetting.cshtml"
                               Write(Url.Action("PrintSetting"));

            
            #line default
            #line hidden
WriteLiteral("\', { stype: $(\"#SType\").val() });\r\n                    }, error: function () {\r\n " +
"                       // handle error\r\n                    }\r\n                }" +
");\r\n                return false;\r\n            });\r\n        });\r\n    </script>\r\n" +
"\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
