#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Oaww.Entity;
    using Oaww.Entity.SET;
    using Oaww.HtmlHelp;
    using Oaww.Utility;
    using Oaww.ViewModel;
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Search;
    using Oaww.ViewModel.SiteMap;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/SiteMap/SiteMapEdit.cshtml")]
    public partial class _Areas_webadmin_Views_SiteMap_SiteMapEdit_cshtml : System.Web.Mvc.WebViewPage<SiteMapEditModel>
    {
        public _Areas_webadmin_Views_SiteMap_SiteMapEdit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
  
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"page-bar\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 182), Tuple.Create("\"", 216)
            
            #line 9 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
, Tuple.Create(Tuple.Create("", 189), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 189), false)
);

WriteLiteral(">Home</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 313), Tuple.Create("\"", 348)
            
            #line 13 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
, Tuple.Create(Tuple.Create("", 320), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Model")
            
            #line default
            #line hidden
, 320), false)
);

WriteLiteral(">模組元件</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 445), Tuple.Create("\"", 482)
            
            #line 17 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
, Tuple.Create(Tuple.Create("", 452), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","SiteMap")
            
            #line default
            #line hidden
, 452), false)
);

WriteLiteral(">網站導覽</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">編輯</a>\r\n        </li>\r\n    </ul>\r\n\r\n</div>\r\n<!--page bar end-->\r\n<!--message sta" +
"rt-->\r\n<div");

WriteLiteral(" class=\"title_01\"");

WriteLiteral(">");

            
            #line 28 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                 Write(Model.ModelName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<div");

WriteLiteral(" class=\"portlet light bordered\"");

WriteLiteral(">\r\n\r\n    <form");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral(" id=\"editform\"");

WriteAttribute("action", Tuple.Create(" action=\'", 839), Tuple.Create("\'", 871)
            
            #line 32 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
     , Tuple.Create(Tuple.Create("", 848), Tuple.Create<System.Object, System.Int32>(Url.Action("SaveItem")
            
            #line default
            #line hidden
, 848), false)
);

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n        <!--<div class=\"search_padding\">\r\n            <button type=\"button\" cl" +
"ass=\"btn blue\" id=\"btn_seoshow\">進階設定</button>\r\n        </div>-->\r\n");

WriteLiteral("        ");

            
            #line 36 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.SiteMapItem.ItemID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 37 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.SiteMapItem.ModelID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 38 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.SiteMapItem.UploadFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.SiteMapItem.UploadFilePath));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 40 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.SiteMapItem.ImageFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(" id=\"form-body2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">無障礙說明</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <textarea");

WriteLiteral(" cols=\"80\"");

WriteLiteral(" id=\"HtmlContent\"");

WriteLiteral(" rows=\"20\"");

WriteLiteral(">");

            
            #line 49 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                                                          Write(HttpUtility.HtmlDecode(Model.SiteMapItem.HtmlContent));

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                            </div>\r\n                        </div>\r\n" +
"                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 2079), Tuple.Create("\"", 2134)
, Tuple.Create(Tuple.Create("", 2087), Tuple.Create("form-group", 2087), true)
            
            #line 52 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
, Tuple.Create(Tuple.Create(" ", 2097), Tuple.Create<System.Object, System.Int32>(Model.SET_BASE.M_Base03?"":"hide"
            
            #line default
            #line hidden
, 2098), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral(">快速鍵說明</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white language_set\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"display_inline margin_bottom\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn green-meadow\"");

WriteLiteral(" id=\"btn_add\"");

WriteLiteral(">新增 <i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i></button>\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn red\"");

WriteLiteral(" id=\"btn_del\"");

WriteLiteral(">刪除 <i");

WriteLiteral(" class=\"glyphicon glyphicon-trash\"");

WriteLiteral("></i></button>\r\n                                </div>\r\n\r\n                       " +
"         <!--table start-->\r\n                                <table");

WriteLiteral(" class=\"table table-bordered nomarginbottom\"");

WriteLiteral(" id=\"tbl_file\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(">\r\n                                    <thead>\r\n                                 " +
"       <tr>\r\n                                            <th");

WriteLiteral(" width=\"60\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" filed-type=\"delcheckbox\"");

WriteLiteral(">刪除</th>\r\n                                            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                區塊說明\r\n                        " +
"                        <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">限制輸入30字內</div>\r\n                                            </th>\r\n             " +
"                               <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">快速鍵 <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">限制輸入10字內</div></th>\r\n                                            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">介紹 <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">限制輸入100字內</div></th>\r\n                                        </tr>\r\n           " +
"                         </thead>\r\n                                    <tbody>\r\n" +
"");

            
            #line 74 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 74 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                         foreach (var key in Model.siteMapKeys)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <tr");

WriteLiteral(" class=\"tr_file\"");

WriteLiteral(">\r\n                                                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <label");

WriteLiteral(" class=\"mt-checkbox mt-checkbox-single mt-checkbox-outline\"");

WriteLiteral(">\r\n                                                        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"checkboxes chksel\"");

WriteLiteral(">\r\n                                                        <span></span>\r\n       " +
"                                             </label>\r\n                         " +
"                       </td>\r\n                                                <t" +
"d");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"AreaName\"");

WriteLiteral(" name=\"AreaName\"");

WriteLiteral(" maxlength=\"30\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4618), Tuple.Create("\"", 4639)
            
            #line 84 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                                                , Tuple.Create(Tuple.Create("", 4626), Tuple.Create<System.Object, System.Int32>(key.AreaName
            
            #line default
            #line hidden
, 4626), false)
);

WriteLiteral(" />\r\n                                                </td>\r\n                     " +
"                           <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"QuickKey\"");

WriteLiteral(" name=\"QuickKey\"");

WriteLiteral(" maxlength=\"10\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4910), Tuple.Create("\"", 4931)
            
            #line 87 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                                                , Tuple.Create(Tuple.Create("", 4918), Tuple.Create<System.Object, System.Int32>(key.QuickKey
            
            #line default
            #line hidden
, 4918), false)
);

WriteLiteral(" />\r\n                                                </td>\r\n                     " +
"                           <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Introduction\"");

WriteLiteral(" name=\"Introduction\"");

WriteLiteral(" maxlength=\"100\"");

WriteLiteral(" class=\"form-control\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5211), Tuple.Create("\"", 5232)
            
            #line 90 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                                                         , Tuple.Create(Tuple.Create("", 5219), Tuple.Create<System.Object, System.Int32>(key.QuickKey
            
            #line default
            #line hidden
, 5219), false)
);

WriteLiteral(" />\r\n                                                </td>\r\n                     " +
"                       </tr>\r\n");

            
            #line 93 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral(@"                                    </tbody>
                                </table>
                                <!--table end-->
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div");

WriteLiteral(" class=\"text-center search_padding\"");

WriteLiteral(" id=\"div_buttons\"");

WriteLiteral(">\r\n\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(">確認送出</button>\r\n\r\n\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_return\"");

WriteLiteral(">返回列表</button>\r\n        </div>\r\n    </form>\r\n\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5990), Tuple.Create("\"", 6057)
            
            #line 115 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
, Tuple.Create(Tuple.Create("", 5996), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/components-date-time-pickers.min.js")
            
            #line default
            #line hidden
, 5996), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6081), Tuple.Create("\"", 6136)
            
            #line 116 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
, Tuple.Create(Tuple.Create("", 6087), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/bootstrap-datepicker.js")
            
            #line default
            #line hidden
, 6087), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6160), Tuple.Create("\"", 6201)
            
            #line 117 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
, Tuple.Create(Tuple.Create("", 6166), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/custom.js")
            
            #line default
            #line hidden
, 6166), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6225), Tuple.Create("\"", 6277)
            
            #line 118 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
, Tuple.Create(Tuple.Create("", 6231), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ckeditor/ckeditor.js")
            
            #line default
            #line hidden
, 6231), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6301), Tuple.Create("\"", 6347)
            
            #line 119 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
, Tuple.Create(Tuple.Create("", 6307), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/bootbox.min.js")
            
            #line default
            #line hidden
, 6307), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6371), Tuple.Create("\"", 6395)
, Tuple.Create(Tuple.Create("", 6377), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/_html.js")
, 6377), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n\r\n            $(\'#btn_add\').cl" +
"ick(function (evt) {\r\n\r\n                evt.preventDefault();\r\n\r\n               " +
" var html = \'\';\r\n                html += \' <tr class=\"tr_file\">\';\r\n             " +
"   html += \'   <td class=\"text-center\">\';\r\n                html += \'       <labe" +
"l class=\"mt-checkbox mt-checkbox-single mt-checkbox-outline\">\';\r\n               " +
" html += \'           <input type=\"checkbox\" class=\"checkboxes chksel\">\';\r\n      " +
"          html += \'           <span></span>\';\r\n                html += \'       <" +
"/label>\';\r\n                html += \'   </td>\';\r\n                html += \'   <td " +
"class=\"text-center\">\';\r\n                html += \'       <input type=\"text\" id=\"A" +
"reaName\" name=\"AreaName\" class=\"form-control\" maxlength=\"30\" value=\"\" />\';\r\n    " +
"            html += \'   </td>\';\r\n                html += \'   <td class=\"text-cen" +
"ter\">\';\r\n                html += \'       <input type=\"text\" id=\"QuickKey\" name=\"" +
"QuickKey\" class=\"form-control\" maxlength=\"10\" value=\"\" />\';\r\n                htm" +
"l += \'   </td>\';\r\n                html += \'   <td class=\"text-center\">\';\r\n      " +
"          html += \'       <input type=\"text\" id=\"Introduction\" name=\"Introductio" +
"n\" class=\"form-control\" maxlength=\"100\" value=\"\" />\';\r\n                html += \'" +
"   </td>\';\r\n                html += \' </tr>\';\r\n\r\n                if ($(\'#tbl_fil" +
"e>tbody tr\').length == 0) {\r\n                    $(\'#tbl_file>tbody\').append(htm" +
"l);\r\n                }\r\n                else {\r\n                    $(\'#tbl_file" +
">tbody tr:last\').after(html);\r\n                }\r\n            })\r\n\r\n            " +
"$(\'#btn_del\').click(function () {\r\n                $(\'.chksel:checked\').parents(" +
"\'tr\').remove();\r\n            })\r\n\r\n            $(\"#btn_return\").click(function (" +
") { CreatePost(\'");

            
            #line 159 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                                        Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("\'); });\r\n\r\n            var ckedit = CKEDITOR.replace(\'HtmlContent\', {\r\n          " +
"      height: 300,\r\n               filebrowserImageUploadUrl: \'");

            
            #line 163 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                      Write(Url.Action("Upload"));

            
            #line default
            #line hidden
WriteLiteral("?command=QuickUpload&type=Images\',\r\n               filebrowserUploadUrl: \'");

            
            #line 164 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                 Write(Url.Action("UploadFile"));

            
            #line default
            #line hidden
WriteLiteral("?command=QuickUpload&type=Files\',\r\n            });\r\n            CKEDITOR.config.e" +
"nterMode = CKEDITOR.ENTER_BR;\r\n            CKEDITOR.config.shiftEnterMode = CKED" +
"ITOR.ENTER_P;\r\n            CKEDITOR.on(\'instanceReady\', function (ev) {\r\n       " +
"         ev.editor.dataProcessor.writer.setRules(\'p\',\r\n                    {\r\n  " +
"                      indent: false,\r\n                        breakBeforeOpen: f" +
"alse,\r\n                        breakAfterOpen: false,\r\n                        b" +
"reakBeforeClose: false,\r\n                        breakAfterClose: false\r\n       " +
"             });\r\n            });\r\n\r\n            $(\'#editform\').submit(function " +
"(event) {\r\n\r\n               $(\".required\").hide();\r\n                 var inputva" +
"l = $(\"#form-body2 :input\").filter(function () { return $(this).val() == \"\" && $" +
"(this).hasClass(\'checkitem\'); });\r\n                for (var idx = 0; idx < input" +
"val.length; idx++) {\r\n                    $(\"#\" + inputval[idx].name + \"-error\")" +
".show();\r\n                }\r\n                if (inputval.length > 0) { return f" +
"alse; }\r\n\r\n               var formData = new FormData();\r\n               var arr" +
"ay = $(\'#editform\').serializeArray();\r\n               $.each(array, function () " +
"{\r\n                   formData.append(this.name, this.value);\r\n               })" +
";\r\n\r\n                formData.append(\"SiteMapItem.HtmlContent\", _html.encode(CKE" +
"DITOR.instances.HtmlContent.getData()));\r\n\r\n                var i = 0;\r\n        " +
"        $(\'.tr_file\').each(function () {\r\n                    formData.append(\"s" +
"iteMapKeys[\" + i + \"].AreaName\", $(this).find(\'#AreaName\').val());\r\n            " +
"        formData.append(\"siteMapKeys[\" + i + \"].QuickKey\", $(this).find(\'#QuickK" +
"ey\').val());\r\n                    formData.append(\"siteMapKeys[\" + i + \"].Introd" +
"uction\", $(this).find(\'#Introduction\').val());\r\n                    i++;\r\n      " +
"          });\r\n\r\n                $.ajax({\r\n                    url: this.action," +
"\r\n                    data: formData,\r\n                    type: \'POST\',\r\n      " +
"              cache: false,\r\n                    contentType: false,\r\n          " +
"          processData: false,\r\n                    success: function (data) {\r\n " +
"                       alert(data);\r\n                        CreatePost(\'");

            
            #line 213 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                               Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("\', { mainid: \'");

            
            #line 213 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                                                 Write(Model.SiteMapItem.ModelID);

            
            #line default
            #line hidden
WriteLiteral("\'});\r\n                    }, error: function () {\r\n                        // han" +
"dle error\r\n                    }\r\n                });\r\n                return fa" +
"lse;\r\n            });\r\n            if (\'");

            
            #line 220 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
            Write(ViewBag.isview);

            
            #line default
            #line hidden
WriteLiteral("\' == \'Y\') {\r\n                $(\'#sel_unit,#editform :input\').attr(\'disabled\', \'di" +
"sabled\');\r\n\r\n\r\n                var btns = \'<button type=\"button\" class=\"btn blue" +
"\"  onclick=\"window.location.href=\\\'");

            
            #line 224 "..\..\Areas\webadmin\Views\SiteMap\SiteMapEdit.cshtml"
                                                                                               Write(Url.Action("Verify", "Config"));

            
            #line default
            #line hidden
WriteLiteral(@"\'"">返回列表</button> &nbsp;'


                $('#div_buttons').empty().append(btns);
            }
        });

        function callpreview() {
            var htmlcontent = CKEDITOR.instances.HtmlContent.getData();
            if (htmlcontent == """") { htmlcontent = ""</br>"" }
            bootbox.alert({
                title: ""預覽"",
                message: htmlcontent,
                size: 'large'
            });
        }
    </script>

");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
