#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Oaww.Entity;
    using Oaww.Entity.SET;
    using Oaww.HtmlHelp;
    using Oaww.Utility;
    
    #line 1 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
    using Oaww.ViewModel;
    
    #line default
    #line hidden
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Search;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/SEO/Index.cshtml")]
    public partial class _Areas_webadmin_Views_SEO_Index_cshtml : System.Web.Mvc.WebViewPage<SEOViewModel>
    {
        public _Areas_webadmin_Views_SEO_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
  
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!--page bar start-->\r\n<div");

WriteLiteral(" class=\"page-bar all_width\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 237), Tuple.Create("\"", 271)
            
            #line 12 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
, Tuple.Create(Tuple.Create("", 244), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 244), false)
);

WriteLiteral(">Home</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 368), Tuple.Create("\"", 403)
            
            #line 16 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
, Tuple.Create(Tuple.Create("", 375), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Model")
            
            #line default
            #line hidden
, 375), false)
);

WriteLiteral(">模組管理</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        ");

WriteLiteral("\r\n    </ul>\r\n</div>\r\n<!--page bar end-->\r\n<!--message start-->\r\n<div");

WriteLiteral(" class=\"title_01\"");

WriteLiteral(">SEO優化設定</div>\r\n<div");

WriteLiteral(" class=\"portlet light bordered\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral(" id=\"editform\"");

WriteAttribute("action", Tuple.Create(" action=\'", 746), Tuple.Create("\'", 774)
            
            #line 28 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
     , Tuple.Create(Tuple.Create("", 755), Tuple.Create<System.Object, System.Int32>(Url.Action("Save")
            
            #line default
            #line hidden
, 755), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
   Write(Html.HiddenFor(Model => Model.ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 30 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
   Write(Html.HiddenFor(Model => Model.TypeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(" id=\"div_seo\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(" id=\"form-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">網頁標題名稱 (Title)</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 38 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                           Write(Html.EditorFor(model => model.WebsiteTitle, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">網頁內容摘要 (Description)</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <textarea");

WriteLiteral(" cols=\"80\"");

WriteLiteral(" id=\"Description\"");

WriteLiteral(" rows=\"8\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" maxlength=\"500\"");

WriteLiteral(">");

            
            #line 44 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                                              Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                            </div>\r\n                        </div>\r\n" +
"                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">網頁內容關鍵字 (Keywords)</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white form-horizontal\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" id=\"Keywords_1\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control  input-small\"");

WriteLiteral(" style=\"display:inline-block;margin:2px 0;\"");

WriteLiteral(" name=\"Keywords[0]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2489), Tuple.Create("\"", 2515)
            
            #line 50 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 2497), Tuple.Create<System.Object, System.Int32>(Model.Keywords[0]
            
            #line default
            #line hidden
, 2497), false)
);

WriteLiteral(" />\r\n                                <input");

WriteLiteral(" id=\"Keywords_2\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control  input-small\"");

WriteLiteral(" style=\"display:inline-block;margin:2px 0;\"");

WriteLiteral(" name=\"Keywords[1]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2683), Tuple.Create("\"", 2709)
            
            #line 51 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 2691), Tuple.Create<System.Object, System.Int32>(Model.Keywords[1]
            
            #line default
            #line hidden
, 2691), false)
);

WriteLiteral(" />\r\n                                <input");

WriteLiteral(" id=\"Keywords_3\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control  input-small\"");

WriteLiteral(" style=\"display:inline-block;margin:2px 0;\"");

WriteLiteral(" name=\"Keywords[2]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2877), Tuple.Create("\"", 2903)
            
            #line 52 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 2885), Tuple.Create<System.Object, System.Int32>(Model.Keywords[2]
            
            #line default
            #line hidden
, 2885), false)
);

WriteLiteral(" />\r\n                                <input");

WriteLiteral(" id=\"Keywords_4\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control  input-small\"");

WriteLiteral(" style=\"display:inline-block;margin:2px 0;\"");

WriteLiteral(" name=\"Keywords[3]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3071), Tuple.Create("\"", 3097)
            
            #line 53 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 3079), Tuple.Create<System.Object, System.Int32>(Model.Keywords[3]
            
            #line default
            #line hidden
, 3079), false)
);

WriteLiteral(" />\r\n                                <input");

WriteLiteral(" id=\"Keywords_5\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control  input-small\"");

WriteLiteral(" style=\"display:inline-block;margin:2px 0;\"");

WriteLiteral(" name=\"Keywords[4]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3265), Tuple.Create("\"", 3291)
            
            #line 54 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 3273), Tuple.Create<System.Object, System.Int32>(Model.Keywords[4]
            
            #line default
            #line hidden
, 3273), false)
);

WriteLiteral(" />\r\n                                <input");

WriteLiteral(" id=\"Keywords_6\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control  input-small\"");

WriteLiteral(" style=\"display:inline-block;margin:2px 0;\"");

WriteLiteral(" name=\"Keywords[5]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3459), Tuple.Create("\"", 3485)
            
            #line 55 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 3467), Tuple.Create<System.Object, System.Int32>(Model.Keywords[5]
            
            #line default
            #line hidden
, 3467), false)
);

WriteLiteral(" />\r\n                                <input");

WriteLiteral(" id=\"Keywords_7\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control  input-small\"");

WriteLiteral(" style=\"display:inline-block;margin:2px 0;\"");

WriteLiteral(" name=\"Keywords[6]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3653), Tuple.Create("\"", 3679)
            
            #line 56 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 3661), Tuple.Create<System.Object, System.Int32>(Model.Keywords[6]
            
            #line default
            #line hidden
, 3661), false)
);

WriteLiteral(" />\r\n                                <input");

WriteLiteral(" id=\"Keywords_8\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control  input-small\"");

WriteLiteral(" style=\"display:inline-block;margin:2px 0;\"");

WriteLiteral(" name=\"Keywords[7]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3847), Tuple.Create("\"", 3873)
            
            #line 57 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 3855), Tuple.Create<System.Object, System.Int32>(Model.Keywords[7]
            
            #line default
            #line hidden
, 3855), false)
);

WriteLiteral(" />\r\n                                <input");

WriteLiteral(" id=\"Keywords_9\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control  input-small\"");

WriteLiteral(" style=\"display:inline-block;margin:2px 0;\"");

WriteLiteral(" name=\"Keywords[8]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4041), Tuple.Create("\"", 4067)
            
            #line 58 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 4049), Tuple.Create<System.Object, System.Int32>(Model.Keywords[8]
            
            #line default
            #line hidden
, 4049), false)
);

WriteLiteral(" />\r\n                                <input");

WriteLiteral(" id=\"Keywords_10\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control  input-small\"");

WriteLiteral(" style=\"display:inline-block;margin:2px 0;\"");

WriteLiteral(" name=\"Keywords[9]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4236), Tuple.Create("\"", 4262)
            
            #line 59 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                                                           , Tuple.Create(Tuple.Create("", 4244), Tuple.Create<System.Object, System.Int32>(Model.Keywords[9]
            
            #line default
            #line hidden
, 4244), false)
);

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n\r\n                </div>\r\n\r\n            </div>\r\n        </di" +
"v>\r\n        <div");

WriteLiteral(" class=\"text-center search_padding\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(">確認送出</button>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"page_line\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"title_01\"");

WriteLiteral(">功能說明</div>\r\n        <div");

WriteLiteral(" class=\"content_font\"");

WriteLiteral(">\r\n            一般稱SEO全稱為「<span");

WriteLiteral(" class=\"red\"");

WriteLiteral(">Search Engine Optimization</span>」，也就是搜索引擎優化。網站經專業的優化程序處理後，將對於各大搜索引擎之搜尋結果將會有明顯的排" +
"序提升。網站優化的目的在於合理及專業的程序，是較具長遠性的作法，目的是使搜索引擎能更明確網站屬性及內容，做最恰當的歸類，進而迅速提高排名及提升網站曝光率。本功能" +
"有助於提升網站於搜尋結果中的排序，所有輸入的內容請詳加規劃。<br><br>\r\n            <span");

WriteLiteral(" class=\"red\"");

WriteLiteral(">註：使用本功能將不保證絕對排名及實質效益，搜尋結果更新須至少7個工作天以上。</span>\r\n        </div>\r\n    </form>\r\n");

DefineSection("scripts", () => {

            
            #line 78 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
    
            
            #line default
            #line hidden
WriteLiteral(@"
        <script>
            $(function () {
                $('#editform').submit(function (event) {
                    var formData = new FormData();
                    var array = $('#editform').serializeArray();
                    $.each(array, function () {
                        formData.append(this.name, this.value);
                    });
                    formData.append(""Description"", encodeURIComponent($('#Description').val()));
                    $.ajax({
                        url: this.action,
                        data: formData,
                        type: 'POST',
                        cache: false,
                         headers: {
                            RequestVerificationToken: '");

            
            #line 94 "..\..\Areas\webadmin\Views\SEO\Index.cshtml"
                                                  Write(CommonRazorFunctions.GetAntiForgery());

            
            #line default
            #line hidden
WriteLiteral(@"'
                        },
                        contentType: false,
                        processData: false,
                        success: function (data) {
                            if (data == """") {
                                alert(""儲存成功"");
                            } else {
                                alert(data);
                            }
                            location.reload();
                        }, error: function () {
                            // handle error
                        }
                    });

                    return false;
                })
            });
        </script>

    ");

});

WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
