#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Oaww.Entity;
    using Oaww.Entity.SET;
    using Oaww.HtmlHelp;
    using Oaww.Utility;
    using Oaww.ViewModel;
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Lang;
    using Oaww.ViewModel.Search;
    using Oaww.ViewModel.SiteMap;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/ExclusiveLayout/MessageEdit.cshtml")]
    public partial class _Areas_webadmin_Views_ExclusiveLayout_MessageEdit_cshtml : System.Web.Mvc.WebViewPage<ExclusiveLayoutViewModel>
    {
        public _Areas_webadmin_Views_ExclusiveLayout_MessageEdit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
  
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";

    List<SelectListItem> Group = Model.SET_LAYOUT_GROUPs.Select(t => new SelectListItem() { Value = t.ID.ToString(), Text = t.GROUP_NAME }).ToList();
    List<SelectListItem> Users = Model.Users.Select(t => new SelectListItem() { Value = t.ID.ToString(), Text = t.User_Name }).ToList();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"page-bar\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 481), Tuple.Create("\"", 515)
            
            #line 12 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 488), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 488), false)
);

WriteLiteral(">Home</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 612), Tuple.Create("\"", 647)
            
            #line 16 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 619), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Model")
            
            #line default
            #line hidden
, 619), false)
);

WriteLiteral(">模組元件</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 744), Tuple.Create("\"", 771)
            
            #line 20 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 751), Tuple.Create<System.Object, System.Int32>(Url.Action("Index")
            
            #line default
            #line hidden
, 751), false)
);

WriteLiteral(">專屬版面</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">編輯</a>\r\n        </li>\r\n    </ul>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"title_01\"");

WriteLiteral(">");

            
            #line 29 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                  Write(Model.ExclusiveLayout.ID <= 0 ? "新增" : "修改");

            
            #line default
            #line hidden
WriteLiteral("專屬版面</div>\r\n<div");

WriteLiteral(" class=\"portlet light bordered\"");

WriteLiteral(">\r\n\r\n    <form");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral(" id=\"editform\"");

WriteAttribute("action", Tuple.Create(" action=\'", 1117), Tuple.Create("\'", 1149)
            
            #line 32 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
    , Tuple.Create(Tuple.Create("", 1126), Tuple.Create<System.Object, System.Int32>(Url.Action("SaveItem")
            
            #line default
            #line hidden
, 1126), false)
);

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("        ");

            
            #line 34 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ExclusiveLayout.ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 35 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ExclusiveLayout.Enabled));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 36 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ExclusiveLayout.Lang_ID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 37 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
   Write(Html.HiddenFor(m => m.ExclusiveLayout.ImageFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 38 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
   Write(Html.HiddenFor(m => m.ExclusiveLayout.ImageFileOrgName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(" id=\"form-body2\"");

WriteLiteral(">\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">");

            
            #line 45 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                                                                             Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 群組</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 47 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                           Write(Html.DropDownListFor(m => m.ExclusiveLayout.GroupID, Group, new { @class = "form-control_1 checkitem" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"Title-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">群組 必須填寫！</span>\r\n                            </div>\r\n                        </d" +
"iv>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">");

            
            #line 52 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                                                                             Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 管理者</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 54 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                           Write(Html.DropDownListFor(m => m.ExclusiveLayout.Manager, Users, new { @class = "form-control_1 checkitem" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"Title-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">管理者 必須填寫！</span>\r\n                            </div>\r\n                        </" +
"div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">");

            
            #line 59 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                                                                             Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 版面名稱</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 61 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                           Write(Html.TextBoxFor(m => m.ExclusiveLayout.Name, new { @class = "form-control checkitem", @maxlength = "50" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">限制輸入50字內</div>\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"Title-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">版面名稱 必須填寫！</span>\r\n                            </div>\r\n                        <" +
"/div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">");

            
            #line 67 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                                                                             Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 網址/(名稱)</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 69 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                           Write(Html.TextBoxFor(m => m.ExclusiveLayout.URL, new { @class = "form-control checkitem", @maxlength = "50" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">限制輸入50字內，且只能輸入英數，第一個字不能為數字</div>\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"Title-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">版面名稱 必須填寫！</span>\r\n                            </div>\r\n                        <" +
"/div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">備註</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 77 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                           Write(Html.TextAreaFor(m => m.ExclusiveLayout.Remark, new { @row = 5, @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"form-group bg-grey_1\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral(">視覺圖片</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" id=\"div_oldfile\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5015), Tuple.Create("\"", 5111)
            
            #line 85 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 5022), Tuple.Create<System.Object, System.Int32>(Model.ExclusiveLayout.ImagelUrl==null?"#":Url.Content(Model.ExclusiveLayout.ImagelUrl)
            
            #line default
            #line hidden
, 5022), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(">");

            
            #line 85 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                                                                                                                                                        Write(Model.ExclusiveLayout.ImageFileOrgName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        <label");

WriteLiteral(" style=\"color:blue;margin-left:10px;cursor:pointer\"");

WriteLiteral(" id=\"delimage\"");

WriteLiteral(">刪除</label>\r\n                                    </div>\r\n                        " +
"            <div");

WriteLiteral(" style=\"display:inline\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" id=\"file_image\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(" name=\"ImageFile\"");

WriteLiteral(" accept=\"image/*\"");

WriteLiteral(" />\r\n                                        <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(@">檔案類型jpg、png、gif，建議檔案大小2MB內，尺寸寬度2000*400px內</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div");

WriteLiteral(" class=\"text-center search_padding\"");

WriteLiteral(" id=\"div_buttons\"");

WriteLiteral(">\r\n\r\n            <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_submit\"");

WriteLiteral(">確認送出</button>\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_return\"");

WriteLiteral(">返回列表</button>\r\n\r\n        </div>\r\n    </form>\r\n\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6199), Tuple.Create("\"", 6240)
            
            #line 110 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 6205), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/custom.js")
            
            #line default
            #line hidden
, 6205), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6264), Tuple.Create("\"", 6289)
, Tuple.Create(Tuple.Create("", 6270), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Common.js")
, 6270), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            if (\'");

            
            #line 114 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
            Write(Model.ExclusiveLayout.ID);

            
            #line default
            #line hidden
WriteLiteral("\'>0 && \'");

            
            #line 114 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                                             Write(Model.ExclusiveLayout.ImageFileName);

            
            #line default
            #line hidden
WriteLiteral(@"'!='') {
                $('#div_oldfile').show();
            }
            $('#delimage').click(function () {
                $('#div_oldfile').hide();
                $('#ExclusiveLayout_ImageFileName').val('');
                $('#ExclusiveLayout_ImageFileOrgName').val('');
            });

            $(""#btn_return"").click(function () { CreatePost('");

            
            #line 123 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                                                        Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("\', null);});\r\n\r\n            $(\'#editform\').submit(function (event) {\r\n\r\n         " +
"      $(\".required\").hide();\r\n                 var inputval = $(\"#form-body2 :in" +
"put\").filter(function () { return $(this).val() == \"\" && $(this).hasClass(\'check" +
"item\'); });\r\n                for (var idx = 0; idx < inputval.length; idx++) {\r\n" +
"                    $(\"#\" + inputval[idx].name + \"-error\").show();\r\n            " +
"    }\r\n                if (inputval.length > 0) { return false; }\r\n\r\n           " +
"     var file = $(\"#file_image\");\r\n                var _validFileExtensions = [\"" +
".jpg\", \".png\", \".gif\", \".jpeg\"];\r\n                var sFileName = file.val();\r\n " +
"               if (sFileName.length > 0) {\r\n                    var blnValid = f" +
"alse;\r\n                    for (var j = 0; j < _validFileExtensions.length; j++)" +
" {\r\n                        var sCurExtension = _validFileExtensions[j];\r\n      " +
"                  if (sFileName.substr(sFileName.length - sCurExtension.length, " +
"sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {\r\n         " +
"                   blnValid = true;\r\n                            break;\r\n       " +
"                 }\r\n                    }\r\n                    if (!blnValid) {\r" +
"\n                        alert(\"只能上傳Image檔案\");\r\n                        file.out" +
"erHTML = file.outerHTML;\r\n                        return false;\r\n               " +
"     }\r\n                }\r\n\r\n               var formData = new FormData();\r\n    " +
"           var array = $(\'#editform\').serializeArray();\r\n               $.each(a" +
"rray, function () {\r\n                   formData.append(this.name, this.value);\r" +
"\n               });\r\n\r\n                var images = $(\'#file_image\').get(0).file" +
"s;\r\n                if (images.length > 0) {\r\n                    formData.appen" +
"d(\"ExclusiveLayout.ImageFile\", images[0]);\r\n                    if ($(\'#ImageFil" +
"eDesc\').val() == \"\") {\r\n                        $(\'#ImageFileDesc-error\').show()" +
";\r\n                        iscon = false;\r\n                    }\r\n              " +
"  } else {\r\n                    formData.append(\"ExclusiveLayout.ImageFile\", nul" +
"l);\r\n                    if ($(\'#ImageFileName\').val() != \"\") {\r\n               " +
"         if ($(\'#ImageFileDesc\').val() == \"\") {\r\n                            $(\'" +
"#ImageFileDesc-error\').show();\r\n                            iscon = false;\r\n    " +
"                    }\r\n                    }\r\n                }\r\n\r\n\r\n           " +
"     $.ajax({\r\n                    url: this.action,\r\n                    data: " +
"formData,\r\n                    type: \'POST\',\r\n                    cache: false,\r" +
"\n                    contentType: false,\r\n                    processData: false" +
",\r\n                    success: function (data) {\r\n                        alert" +
"(data);\r\n                        if (data == \'新增成功\' || data == \'修改成功\') {\r\n      " +
"                      CreatePost(\'");

            
            #line 187 "..\..\Areas\webadmin\Views\ExclusiveLayout\MessageEdit.cshtml"
                                   Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n                        }\r\n                    }, error: function () {\r\n    " +
"                    // handle error\r\n                    }\r\n                });\r" +
"\n                return false;\r\n            });\r\n\r\n        });\r\n\r\n\r\n    </script" +
">\r\n\r\n");

});

        }
    }
}
#pragma warning restore 1591
