#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Oaww.Entity;
    using Oaww.Entity.SET;
    using Oaww.HtmlHelp;
    using Oaww.Utility;
    using Oaww.ViewModel;
    using Oaww.ViewModel.Config;
    using Oaww.ViewModel.Lang;
    using Oaww.ViewModel.Search;
    using Oaww.ViewModel.SiteMap;
    using Template;
    using webadmin;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/webadmin/Views/Message/MessageEdit.cshtml")]
    public partial class _Areas_webadmin_Views_Message_MessageEdit_cshtml : System.Web.Mvc.WebViewPage<MessageEditModel>
    {
        public _Areas_webadmin_Views_Message_MessageEdit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
  
    Layout = "~/Areas/webadmin/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n<!-- 載入 summernote 中文語系 -->\r\n<!--page bar start-->\r\n<div");

WriteLiteral(" class=\"page-bar\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"page-breadcrumb\"");

WriteLiteral(">\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 304), Tuple.Create("\"", 338)
            
            #line 11 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 311), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 311), false)
);

WriteLiteral(">Home</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 435), Tuple.Create("\"", 470)
            
            #line 15 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 442), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Model")
            
            #line default
            #line hidden
, 442), false)
);

WriteLiteral(">模組元件</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 567), Tuple.Create("\"", 624)
            
            #line 19 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 574), Tuple.Create<System.Object, System.Int32>(Url.Action("Index",Model.SET_MESSAGE.M_MESSAGE06)
            
            #line default
            #line hidden
, 574), false)
);

WriteLiteral(">");

            
            #line 19 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                    Write(Model.SET_MESSAGE.M_MESSAGE05);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 747), Tuple.Create("\"", 836)
            
            #line 23 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 754), Tuple.Create<System.Object, System.Int32>(Url.Action("ModelItem",Model.SET_MESSAGE.M_MESSAGE06,new { mainid=Model.ModelID})
            
            #line default
            #line hidden
, 754), false)
);

WriteLiteral(">清單</a>\r\n            <i");

WriteLiteral(" class=\"fa fa-circle\"");

WriteLiteral("></i>\r\n        </li>\r\n        <li>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">編輯</a>\r\n        </li>\r\n    </ul>\r\n\r\n</div>\r\n<!--page bar end-->\r\n<!--message sta" +
"rt-->\r\n<div");

WriteLiteral(" class=\"title_01\"");

WriteLiteral(">");

            
            #line 34 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                 Write(Model.ModelName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n<div");

WriteLiteral(" class=\"portlet light bordered\"");

WriteLiteral(">\r\n\r\n    <form");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral(" id=\"editform\"");

WriteAttribute("action", Tuple.Create(" action=\'", 1191), Tuple.Create("\'", 1223)
            
            #line 38 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
    , Tuple.Create(Tuple.Create("", 1200), Tuple.Create<System.Object, System.Int32>(Url.Action("SaveItem")
            
            #line default
            #line hidden
, 1200), false)
);

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(">\r\n        <!--<div class=\"search_padding\">\r\n        <button type=\"button\" class=" +
"\"btn blue\" id=\"btn_seoshow\">進階設定</button>\r\n    </div>-->\r\n");

WriteLiteral("        ");

            
            #line 42 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ItemID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 43 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ModelID));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 44 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.UploadFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 45 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.UploadFilePath));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 46 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.UploadFileSize));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 47 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.UploadFileType));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 48 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ImageFileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 49 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.ImageFileOrgName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 50 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.RelateImageName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 51 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
   Write(Html.HiddenFor(Model => Model.RelateImageFileOrgName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"portlet light form-fit bordered\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"portlet-body form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-horizontal form-bordered\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-body\"");

WriteLiteral(" id=\"form-body2\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">");

            
            #line 57 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                             Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 類別</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 59 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                           Write(Html.DropDownList(@Html.IdFor(m => m.Group_ID).ToString(), (IEnumerable<SelectListItem>)ViewBag.grouplist, new { @class = "form_02" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n\r\n         " +
"               <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">");

            
            #line 64 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                             Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 發布日期</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-4 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"date-picker input-daterange\"");

WriteLiteral(" data-date-format=\"yyyy/mm/dd\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 67 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                               Write(Html.EditorFor(model => model.PublicshStr, new { htmlAttributes = new { @class = "form-control checkitem", placeholder = "發佈日期" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"PublicshStr-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">發佈日期 必須填寫！</span>\r\n                                </div>\r\n                     " +
"       </div>\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 bg-grey_1 search_item\"");

WriteLiteral(">顯示日期</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"input-group input-large\"");

WriteLiteral(" style=\"float:left\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"date-picker input-daterange\"");

WriteLiteral(" data-date-format=\"yyyy/mm/dd\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 78 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                   Write(Html.EditorFor(model => model.StDateStr, new { htmlAttributes = new { @class = "form-control", placeholder = "開始日期", @readonly = "readonly" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                   " +
" <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">to</span>\r\n                                    <div");

WriteLiteral(" class=\"date-picker input-daterange\"");

WriteLiteral(" data-date-format=\"yyyy/mm/dd\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 82 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                   Write(Html.EditorFor(model => model.EdDateStr, new { htmlAttributes = new { @class = "form-control", placeholder = "結束日期", @readonly = "readonly" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n                                <div");

WriteLiteral(" class=\"\"");

WriteLiteral(" style=\"float:left; padding-left:5px;\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn blue\"");

WriteLiteral(" id=\"btn_clear\"");

WriteLiteral(">清空</button>\r\n                                </div>\r\n                           " +
" </div>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"form-group hide\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">下架日期</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-4 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"date-picker input-daterange\"");

WriteLiteral(" data-date-format=\"yyyy/mm/dd\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 94 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                               Write(Html.EditorFor(model => model.UnPublicshStr, new { htmlAttributes = new { @class = "form-control input-small", placeholder = "下架日期", @readonly = "readonly" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">");

            
            #line 99 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                             Write(Html.Require());

            
            #line default
            #line hidden
WriteLiteral(" 標題</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" id=\"Title\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" name=\"Title\"");

WriteLiteral(" class=\"form-control checkitem\"");

WriteLiteral(" maxlength=\"500\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5889), Tuple.Create("\"", 5909)
            
            #line 101 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                 , Tuple.Create(Tuple.Create("", 5897), Tuple.Create<System.Object, System.Int32>(Model.Title
            
            #line default
            #line hidden
, 5897), false)
);

WriteLiteral(" />\r\n                                <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">限制輸入500字內</div>\r\n                                <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"Title-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">標題 必須填寫！</span>\r\n                            </div>\r\n                        </d" +
"iv>\r\n\r\n                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 6190), Tuple.Create("\"", 6271)
, Tuple.Create(Tuple.Create("", 6198), Tuple.Create("form-group", 6198), true)
, Tuple.Create(Tuple.Create(" ", 6208), Tuple.Create("bg-grey_1", 6209), true)
            
            #line 107 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create(" ", 6218), Tuple.Create<System.Object, System.Int32>(Model.SET_MESSAGE.M_MESSAGE07 == false ?"hide":""
            
            #line default
            #line hidden
, 6219), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral(">列表圖片</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" id=\"div_oldrelatefile\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6630), Tuple.Create("\"", 6706)
            
            #line 112 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 6637), Tuple.Create<System.Object, System.Int32>(Model.RelateImagelUrl==null?"#":Url.Content(Model.RelateImagelUrl)
            
            #line default
            #line hidden
, 6637), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(">");

            
            #line 112 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                                                                                    Write(Model.RelateImageFileOrgName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                        <label");

WriteLiteral(" style=\"color:blue;margin-left:10px;cursor:pointer\"");

WriteLiteral(" id=\"delrelateimage\"");

WriteLiteral(">刪除</label>\r\n                                    </div>\r\n                        " +
"            <div");

WriteLiteral(" style=\"display:inline\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" id=\"file_relateimage\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(" name=\"ImageFile\"");

WriteLiteral(" accept=\"image/*\"");

WriteLiteral(" />\r\n                                        <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">檔案類型jpg、png、gif，建議檔案大小2MB內，尺寸寬度480*480px內</div>\r\n                               " +
"     </div>\r\n                                </div>\r\n                           " +
" </div>\r\n                        </div>\r\n                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 7428), Tuple.Create("\"", 7499)
, Tuple.Create(Tuple.Create("", 7436), Tuple.Create("form-group", 7436), true)
            
            #line 122 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create(" ", 7446), Tuple.Create<System.Object, System.Int32>(Model.SET_MESSAGE.M_MESSAGE08 == false ?"hide":""
            
            #line default
            #line hidden
, 7447), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">開啟格式設定</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white table_font\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 125 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                           Write(Html.RadioButtonFor(m => m.Link_Mode, "1"));

            
            #line default
            #line hidden
WriteLiteral(" 可開啟內容頁\r\n");

WriteLiteral("                                ");

            
            #line 126 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                           Write(Html.RadioButtonFor(m => m.Link_Mode, "2"));

            
            #line default
            #line hidden
WriteLiteral(" 不可開啟內容頁\r\n                            </div>\r\n                        </div>\r\n   " +
"                     <div");

WriteAttribute("class", Tuple.Create(" class=\"", 7970), Tuple.Create("\"", 8041)
, Tuple.Create(Tuple.Create("", 7978), Tuple.Create("form-group", 7978), true)
            
            #line 129 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create(" ", 7988), Tuple.Create<System.Object, System.Int32>(Model.SET_MESSAGE.M_MESSAGE09 == false ?"hide":""
            
            #line default
            #line hidden
, 7989), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">內容</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <textarea");

WriteLiteral(" cols=\"80\"");

WriteLiteral(" id=\"HtmlContent\"");

WriteLiteral(" rows=\"20\"");

WriteLiteral(">");

            
            #line 132 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                          Write(HttpUtility.HtmlDecode(Model.HtmlContent));

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                            </div>\r\n                        </div>\r\n" +
"                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 8462), Tuple.Create("\"", 8533)
, Tuple.Create(Tuple.Create("", 8470), Tuple.Create("form-group", 8470), true)
            
            #line 135 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create(" ", 8480), Tuple.Create<System.Object, System.Int32>(Model.SET_MESSAGE.M_MESSAGE15 == false ?"hide":""
            
            #line default
            #line hidden
, 8481), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">簡介</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <textarea");

WriteLiteral(" name=\"Introduction\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"Introduction\"");

WriteLiteral(" rows=\"5\"");

WriteLiteral(">");

            
            #line 138 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                                                         Write(Model.Introduction);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n                            </div>\r\n                        </div>\r\n" +
"                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 8962), Tuple.Create("\"", 9043)
, Tuple.Create(Tuple.Create("", 8970), Tuple.Create("form-group", 8970), true)
, Tuple.Create(Tuple.Create(" ", 8980), Tuple.Create("bg-grey_1", 8981), true)
            
            #line 141 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create(" ", 8990), Tuple.Create<System.Object, System.Int32>(Model.SET_MESSAGE.M_MESSAGE10 == false ?"hide":""
            
            #line default
            #line hidden
, 8991), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral(">圖片</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" id=\"div_oldfile\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral("><a");

WriteAttribute("href", Tuple.Create(" href=\"", 9352), Tuple.Create("\"", 9425)
            
            #line 145 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
         , Tuple.Create(Tuple.Create("", 9359), Tuple.Create<System.Object, System.Int32>(Model.ImageUrl == null?"":Url.Content(Model.ImageUrl.AntiXss())
            
            #line default
            #line hidden
, 9359), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(">");

            
            #line 145 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                                                                                                                        Write(Html.Raw(Model.ImageFileOrgName.safeHtmlFragment()));

            
            #line default
            #line hidden
WriteLiteral("</a><label");

WriteLiteral(" style=\"color:blue;margin-left:10px;cursor:pointer\"");

WriteLiteral(" id=\"delimage\"");

WriteLiteral(">刪除</label></div>\r\n                                    <label");

WriteLiteral(" for=\"ImageFile\"");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">圖片上傳</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" id=\"file_image\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(" name=\"ImageFile\"");

WriteLiteral(" accept=\"image/*\"");

WriteLiteral(" />\r\n                                        <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">檔案類型jpg、png、gif，建議檔案大小2MB內，尺寸寬度1000px內</div>\r\n                                  " +
"  </div>\r\n                                </div>\r\n                              " +
"  <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">圖片說明</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 155 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                   Write(Html.EditorFor(model => model.ImageFileDesc, new { htmlAttributes = new { @class = "form-control mobile_input display_inline", @maxlength = "75" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">限制輸入75字內</div>\r\n                                        <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"ImageFileDesc-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">圖片說明 必須填寫！</span>\r\n                                    </div>\r\n                 " +
"               </div>\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">圖片位置</label>\r\n                                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                                        <select");

WriteAttribute("name", Tuple.Create(" name=\"", 10973), Tuple.Create("\"", 11023)
            
            #line 163 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 10980), Tuple.Create<System.Object, System.Int32>(Html.IdFor(model=>model.ImageFileLocation)
            
            #line default
            #line hidden
, 10980), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 11024), Tuple.Create("\"", 11072)
            
            #line 163 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                      , Tuple.Create(Tuple.Create("", 11029), Tuple.Create<System.Object, System.Int32>(Html.IdFor(model=>model.ImageFileLocation)
            
            #line default
            #line hidden
, 11029), false)
);

WriteLiteral(" class=\"form-control w-auto\"");

WriteLiteral("><option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">左</option><option");

WriteLiteral(" value=\"2\"");

WriteLiteral(">中</option><option");

WriteLiteral(" value=\"3\"");

WriteLiteral(">右</option></select>\r\n                                    </div>\r\n               " +
"                 </div>\r\n                            </div>\r\n                   " +
"     </div>\r\n\r\n                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 11379), Tuple.Create("\"", 11459)
, Tuple.Create(Tuple.Create("", 11387), Tuple.Create("form-group", 11387), true)
, Tuple.Create(Tuple.Create(" ", 11397), Tuple.Create("bg-grey_1", 11398), true)
            
            #line 169 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create(" ", 11407), Tuple.Create<System.Object, System.Int32>(Model.SET_MESSAGE.M_MESSAGE03 ==false ?"hide":""
            
            #line default
            #line hidden
, 11408), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 search_item\"");

WriteLiteral(">圖片上傳</div>\r\n                            <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 bg-white mobile_white language_set\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"display_inline margin_bottom\"");

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn green-meadow\"");

WriteLiteral(" id=\"btn_image_add\"");

WriteLiteral(">新增 <i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i></button>\r\n                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn red\"");

WriteLiteral(" id=\"btn_image_del\"");

WriteLiteral(">刪除 <i");

WriteLiteral(" class=\"glyphicon glyphicon-trash\"");

WriteLiteral("></i></button>\r\n                                </div>\r\n\r\n                       " +
"         <!--table start-->\r\n                                <table");

WriteLiteral(" class=\"table table-bordered nomarginbottom\"");

WriteLiteral(" id=\"tbl_image\"");

WriteLiteral(" border=\"0\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"0\"");

WriteLiteral(">\r\n                                    <thead>\r\n                                 " +
"       <tr>\r\n                                            <th");

WriteLiteral(" width=\"60\"");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(" filed-type=\"delcheckbox\"");

WriteLiteral(">刪除</th>\r\n                                            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">圖片上傳</th>\r\n                                            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">圖片預覽</th>\r\n                                            <th");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">圖片說明</th>\r\n                                        </tr>\r\n                      " +
"              </thead>\r\n                                    <tbody>\r\n");

            
            #line 188 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 188 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                         foreach (var fileDownloadFile in Model.messageImages)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <tr");

WriteLiteral(" class=\"tr_image\"");

WriteLiteral(">\r\n                                                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <label");

WriteLiteral(" class=\"mt-checkbox mt-checkbox-single mt-checkbox-outline\"");

WriteLiteral(">\r\n                                                        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"checkboxes image\"");

WriteLiteral(">\r\n                                                        <span></span>\r\n       " +
"                                             </label>\r\n                         " +
"                       </td>\r\n                                                <t" +
"d");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" id=\"div_olduploadimgge\"");

WriteLiteral(">\r\n                                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UploadFileName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 13774), Tuple.Create("\"", 13815)
            
            #line 199 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                       , Tuple.Create(Tuple.Create(" ", 13782), Tuple.Create<System.Object, System.Int32>(fileDownloadFile.UploadFileName
            
            #line default
            #line hidden
, 13783), false)
);

WriteLiteral(" />\r\n                                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UploadFilePath\"");

WriteAttribute("value", Tuple.Create(" value=\"", 13917), Tuple.Create("\"", 13958)
            
            #line 200 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                       , Tuple.Create(Tuple.Create(" ", 13925), Tuple.Create<System.Object, System.Int32>(fileDownloadFile.UploadFilePath
            
            #line default
            #line hidden
, 13926), false)
);

WriteLiteral(" />\r\n\r\n                                                    </div>\r\n              " +
"                                      <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"uploadfile\"");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(" accept=\"image/*\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"required \"");

WriteLiteral(">建議檔案大小5MB內</span>\r\n                                                </td>\r\n      " +
"                                          <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 14435), Tuple.Create("\"", 14501)
            
            #line 207 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 14441), Tuple.Create<System.Object, System.Int32>(Url.Action("ImageDownLoad",new {FID=fileDownloadFile.FID })
            
            #line default
            #line hidden
, 14441), false)
);

WriteLiteral(" style=\"height:100px\"");

WriteLiteral(" target=\"preview\"");

WriteLiteral(">\r\n                                                </td>\r\n                       " +
"                         <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <input");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 14742), Tuple.Create("\"", 14782)
            
            #line 210 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 14750), Tuple.Create<System.Object, System.Int32>(fileDownloadFile.UploadFileDesc
            
            #line default
            #line hidden
, 14750), false)
);

WriteLiteral(" id=\"UploadFileDesc\"");

WriteLiteral(" maxlength=\"75\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"UploadFileDesc-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">檔案說明 必須填寫！</span>\r\n                                                    <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">限制輸入75字內</div>\r\n                                                </td>\r\n         " +
"                                   </tr>\r\n");

            
            #line 215 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </tbody>\r\n                                </t" +
"able>\r\n                                <!--table end-->\r\n                       " +
"     </div>\r\n                        </div>\r\n\r\n                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 15454), Tuple.Create("\"", 15524)
, Tuple.Create(Tuple.Create("", 15462), Tuple.Create("form-group", 15462), true)
            
            #line 222 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create(" ", 15472), Tuple.Create<System.Object, System.Int32>(Model.SET_MESSAGE.M_MESSAGE11 ==false ?"hide":""
            
            #line default
            #line hidden
, 15473), false)
);

WriteLiteral(@" "" >
                            <div class=""col-md-2 col-sm-12 col-xs-12 search_item"">相關連結</div>
                            <div class=""col-md-10  col-sm-12 col-xs-12 bg-white mobile_white"">
                                <div class=""col-md-12"">
                                    <label class=""col-md-2"">相關連結</label>
                                    <div class=""col-md-10"">
");

WriteLiteral("                                        ");

            
            #line 228 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                   Write(Html.EditorFor(model => model.LinkUrl, new { htmlAttributes = new { @class = "form-control", @maxlength = "1000" } }));

            
            #line default
            #line hidden
WriteLiteral(@"
                                        <div class=""red"">限制輸入1000字內</div>
                                    </div>
                                </div>
                                <div class=""col-md-12"">
                                    <label class=""col-md-2"">連結說明</label>
                                    <div class=""col-md-10 margin_bottom"">
");

WriteLiteral("                                        ");

            
            #line 235 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                   Write(Html.EditorFor(model => model.LinkUrlDesc, new { htmlAttributes = new { @class = "form-control", @maxlength = "200" } }));

            
            #line default
            #line hidden
WriteLiteral(@"
                                        <div class=""red"">限制輸入200字內</div>
                                        <span class=""required"" id=""LinkUrlDesc-error"" style=""display:none;"">連結說明 必須填寫！</span>
                                    </div>
                                </div>
                                <div class=""col-md-12"">
                                    <label class=""col-md-2"">開啟方式</label>
                                    <div class=""col-md-10 margin_bottom"">
");

WriteLiteral("                                        ");

            
            #line 243 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                   Write(Html.RadioButtonFor(model => model.OpenMode, 1, new { style = "margin-left :0px", @checked = "checked" }));

            
            #line default
            #line hidden
WriteLiteral(" 原視窗<br />\r\n");

WriteLiteral("                                        ");

            
            #line 244 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                   Write(Html.RadioButtonFor(model => model.OpenMode, 2, new { style = "" }));

            
            #line default
            #line hidden
WriteLiteral(" 新視窗<br />\r\n                                    </div>\r\n                         " +
"       </div>\r\n                            </div>\r\n                        </div" +
">\r\n\r\n                        <div class=\"form-group bg-grey_1 ");

            
            #line 250 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                     Write(Model.SET_MESSAGE.M_MESSAGE04 ?"hide":"");

            
            #line default
            #line hidden
WriteLiteral(@""">
                            <div class=""col-md-2 col-sm-12 search_item"">檔案上傳</div>
                            <div class=""col-md-10 col-sm-12 bg-white mobile_white language_set"">
                                <div class=""col-md-12"">
                                    <div id=""div_olduploadfile"" style=""display:none""><a href=""");

            
            #line 254 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                                         Write(Url.Action("FileDownLoad2"));

            
            #line default
            #line hidden
WriteLiteral("?modelid=");

            
            #line 254 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                                                                              Write(Model.ModelID);

            
            #line default
            #line hidden
WriteLiteral("&&itemid=");

            
            #line 254 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                                                                                                     Write(Model.ItemID);

            
            #line default
            #line hidden
WriteLiteral("\" target=\"preview\">");

            
            #line 254 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                                                                                                                                     Write(Model.UploadFileName);

            
            #line default
            #line hidden
WriteLiteral(@"</a><label style=""color:blue;margin-left:10px;cursor:pointer"" id=""delupfile"">刪除</label></div>

                                    <div id=""div_nofile"" style=""display:inline"">
                                        <label for=""UploadFile"" class=""col-md-2"">檔案上傳</label>
                                        <div class=""col-md-10"">
                                            <input type=""file"" id=""SingleUploadfile"" class=""display_inline"" name=""UploadFile"">
                                            <span class=""required"">建議檔案大小5MB內</span>
                                        </div>
                                    </div>
                                </div>
                                <div class=""col-md-12"">
                                    <label class=""col-md-2"">檔案說明</label>
                                    <div class=""col-md-10 margin_bottom"">
");

WriteLiteral("                                        ");

            
            #line 267 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                   Write(Html.EditorFor(model => model.UploadFileDesc, new { htmlAttributes = new { @class = "form-control mobile_input display_inline", @id = "SingleUploadFileDesc" } }));

            
            #line default
            #line hidden
WriteLiteral(@"
                                        <span class=""required"" id=""SingleUploadFileDesc-error"" style=""display:none;"">檔案說明 必須填寫！</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class=""form-group bg-grey_1 ");

            
            #line 274 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                     Write(Model.SET_MESSAGE.M_MESSAGE04 ==false ?"hide":"");

            
            #line default
            #line hidden
WriteLiteral(@""">
                            <div class=""col-md-2 col-sm-12 search_item"">檔案上傳</div>
                            <div class=""col-md-10 col-sm-12 bg-white mobile_white language_set"">
                                <div class=""display_inline margin_bottom"">
                                    <button type=""button"" class=""btn green-meadow"" id=""btn_file_add"">新增 <i class=""fa fa-plus""></i></button>
                                    <button type=""button"" class=""btn red"" id=""btn_file_del"">刪除 <i class=""glyphicon glyphicon-trash""></i></button>
                                </div>

                                <!--table start-->
                                <table class=""table table-bordered nomarginbottom"" id=""tbl_file"" border=""0"" cellspacing=""0"" cellpadding=""0"">
                                    <thead>
                                        <tr>
                                            <th width=""60"" class=""text-center"" filed-type=""delcheckbox"">刪除</th>
                                            <th class=""text-center"">檔案上傳</th>
                                            <th class=""text-center"">標題</th>
                                            <th class=""text-center"">檔案說明</th>
                                        </tr>
                                    </thead>
                                    <tbody>
");

            
            #line 293 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 293 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                         foreach (var fileDownloadFile in Model.fileDownloadFiles)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <tr");

WriteLiteral(" class=\"tr_file\"");

WriteLiteral(">\r\n                                                <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <label");

WriteLiteral(" class=\"mt-checkbox mt-checkbox-single mt-checkbox-outline\"");

WriteLiteral(">\r\n                                                        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"checkboxes chksel\"");

WriteLiteral(">\r\n                                                        <span></span>\r\n       " +
"                                             </label>\r\n                         " +
"                       </td>\r\n                                                <t" +
"d");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" id=\"div_olduploadfile\"");

WriteLiteral(">\r\n                                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UploadFileName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 21880), Tuple.Create("\"", 21921)
            
            #line 304 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                       , Tuple.Create(Tuple.Create(" ", 21888), Tuple.Create<System.Object, System.Int32>(fileDownloadFile.UploadFileName
            
            #line default
            #line hidden
, 21889), false)
);

WriteLiteral(" />\r\n                                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UploadFilePath\"");

WriteAttribute("value", Tuple.Create(" value=\"", 22023), Tuple.Create("\"", 22064)
            
            #line 305 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                       , Tuple.Create(Tuple.Create(" ", 22031), Tuple.Create<System.Object, System.Int32>(fileDownloadFile.UploadFilePath
            
            #line default
            #line hidden
, 22032), false)
);

WriteLiteral(" />\r\n                                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UploadFileSize\"");

WriteAttribute("value", Tuple.Create(" value=\"", 22166), Tuple.Create("\"", 22207)
            
            #line 306 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                       , Tuple.Create(Tuple.Create(" ", 22174), Tuple.Create<System.Object, System.Int32>(fileDownloadFile.UploadFileSize
            
            #line default
            #line hidden
, 22175), false)
);

WriteLiteral(" />\r\n                                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UploadFileType\"");

WriteAttribute("value", Tuple.Create(" value=\"", 22309), Tuple.Create("\"", 22350)
            
            #line 307 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                       , Tuple.Create(Tuple.Create(" ", 22317), Tuple.Create<System.Object, System.Int32>(fileDownloadFile.UploadFileType
            
            #line default
            #line hidden
, 22318), false)
);

WriteLiteral(" />\r\n                                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 22414), Tuple.Create("\"", 22480)
            
            #line 308 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 22421), Tuple.Create<System.Object, System.Int32>(Url.Action("FileDownLoad",new {FID=fileDownloadFile.FID })
            
            #line default
            #line hidden
, 22421), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(">\r\n");

WriteLiteral("                                                            ");

            
            #line 309 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                       Write(fileDownloadFile.UploadFileName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                        </a>\r\n\r\n               " +
"                                     </div>\r\n                                   " +
"                 <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"uploadfile\"");

WriteLiteral(" class=\"display_inline\"");

WriteLiteral(" name=\"UploadFile\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"required \"");

WriteLiteral(">建議檔案大小5MB內</span>\r\n                                                </td>\r\n      " +
"                                          <td");

WriteLiteral(" class=\"text-left\"");

WriteLiteral(">\r\n                                                    <input");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 23141), Tuple.Create("\"", 23172)
            
            #line 317 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 23149), Tuple.Create<System.Object, System.Int32>(fileDownloadFile.Title
            
            #line default
            #line hidden
, 23149), false)
);

WriteLiteral(" id=\"Title\"");

WriteLiteral(" maxlength=\"75\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"Title-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">標題說明 必須填寫！</span>\r\n                                                    <div");

WriteLiteral(" class=\"required\"");

WriteLiteral(">限制輸入75字內</div>\r\n                                                </td>\r\n         " +
"                                       <td");

WriteLiteral(" class=\"text-center\"");

WriteLiteral(">\r\n                                                    <input");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 23645), Tuple.Create("\"", 23685)
            
            #line 322 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 23653), Tuple.Create<System.Object, System.Int32>(fileDownloadFile.UploadFileDesc
            
            #line default
            #line hidden
, 23653), false)
);

WriteLiteral(" id=\"UploadFileDesc\"");

WriteLiteral(" maxlength=\"75\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" class=\"required\"");

WriteLiteral(" id=\"UploadFileDesc-error\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">檔案說明 必須填寫！</span>\r\n                                                    <div");

WriteLiteral(" class=\"red\"");

WriteLiteral(">限制輸入75字內</div>\r\n                                                </td>\r\n         " +
"                                   </tr>\r\n");

            
            #line 327 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </tbody>\r\n                                </t" +
"able>\r\n                                <!--table end-->\r\n                       " +
"     </div>\r\n                        </div>\r\n                        ");

WriteLiteral("\r\n");

            
            #line 376 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 376 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                         if (Model.SET_MESSAGE.M_MESSAGE18.IsNullOrEmpty() == false)
                        {
                            
            
            #line default
            #line hidden
            
            #line 378 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                       Write(Html.Partial(Model.SET_MESSAGE.M_MESSAGE18, Model));

            
            #line default
            #line hidden
            
            #line 378 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                               
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 381 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 381 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                         if (Model.ItemID >= 0 && Model.SET_BASE.M_Base02)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">審核狀態</div>\r\n                                <div");

WriteLiteral(" class=\"col-md-4 col-sm-12 col-xs-12 mobile_white table_font\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 386 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                               Write(Model.VerifyStatus);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n");

WriteLiteral("                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">新增</div>\r\n                                <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 mobile_white language_set\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"exampleInputFile\"");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">人員</label>\r\n                                        <div");

WriteLiteral(" class=\"col-md-10 label_font\"");

WriteLiteral(">");

            
            #line 394 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                     Write(Model.CreateUser);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </div>\r\n                             " +
"       <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">時間</label>\r\n                                        <div");

WriteLiteral(" class=\"col-md-10 label_font\"");

WriteLiteral(">");

            
            #line 398 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                     Write(Model.CreateDatetime);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </div>\r\n                             " +
"   </div>\r\n                            </div>\r\n");

WriteLiteral("                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">最後修改</div>\r\n                                <div");

WriteLiteral(" class=\"col-md-10 col-sm-12 mobile_white language_set\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"exampleInputFile\"");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">人員</label>\r\n                                        <div");

WriteLiteral(" class=\"col-md-10 label_font\"");

WriteLiteral(">");

            
            #line 407 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                     Write(Model.UpdateUser);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </div>\r\n                             " +
"       <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">時間</label>\r\n                                        <div");

WriteLiteral(" class=\"col-md-10 label_font\"");

WriteLiteral(">");

            
            #line 411 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                     Write(Model.UpdateDatetime);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </div>\r\n                             " +
"   </div>\r\n                            </div>\r\n");

WriteLiteral("                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-2 col-sm-12 col-xs-12 search_item\"");

WriteLiteral(">最後審核</div>\r\n                                <div");

WriteLiteral(" class=\"col-md-10 col-sm-12  mobile_white language_set\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" for=\"exampleInputFile\"");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">人員</label>\r\n                                        <div");

WriteLiteral(" class=\"col-md-10 label_font\"");

WriteLiteral(">");

            
            #line 420 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                     Write(Model.VerifyUser);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </div>\r\n                             " +
"       <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                        <label");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">時間</label>\r\n                                        <div");

WriteLiteral(" class=\"col-md-10 label_font\"");

WriteLiteral(">");

            
            #line 424 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                     Write(Model.VerifyDateTime);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </div>\r\n                             " +
"   </div>\r\n                            </div>\r\n");

            
            #line 428 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral(@"                    </div>
                </div>
            </div>
        </div>
        <div class=""text-center search_padding"" id=""div_buttons"">

            <button type=""submit"" class=""btn blue"" id=""btn_submit"">確認送出</button>

            <button type=""button"" class=""btn blue"" id=""btn_return"">返回列表</button>
            <button type=""button"" class=""btn grey-mint "" id=""preview"" onclick=""callpreview()"">預覽</button>
        </div>
    </form>

</div>
");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31885), Tuple.Create("\"", 31952)
            
            #line 444 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 31891), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/components-date-time-pickers.min.js")
            
            #line default
            #line hidden
, 31891), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 31976), Tuple.Create("\"", 32031)
            
            #line 445 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 31982), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/bootstrap-datepicker.js")
            
            #line default
            #line hidden
, 31982), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32055), Tuple.Create("\"", 32096)
            
            #line 446 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 32061), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/custom.js")
            
            #line default
            #line hidden
, 32061), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32120), Tuple.Create("\"", 32172)
            
            #line 447 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 32126), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ckeditor/ckeditor.js")
            
            #line default
            #line hidden
, 32126), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32196), Tuple.Create("\"", 32242)
            
            #line 448 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
, Tuple.Create(Tuple.Create("", 32202), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/bootbox.min.js")
            
            #line default
            #line hidden
, 32202), false)
);

WriteLiteral("></script>\r\n \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32269), Tuple.Create("\"", 32293)
, Tuple.Create(Tuple.Create("", 32275), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/_html.js")
, 32275), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 32317), Tuple.Create("\"", 32342)
, Tuple.Create(Tuple.Create("", 32323), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/Common.js")
, 32323), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            var fileupload = \'" +
"");

            
            #line 454 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                         Write(Model.UploadFileName);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            var selactiveitem = \'");

            
            #line 455 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                            Write(Model.ActiveItemID);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\r\n            $(\'#btn_clear\').click(function () {\r\n                $(\'#StDate" +
"Str\').val(\'\');\r\n                $(\'#EdDateStr\').val(\'\');\r\n            });\r\n     " +
"       $(\'#ImageFileLocation\').val(\'");

            
            #line 461 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                    Write(Model.ImageFileLocation);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n\r\n            var fileupload = \'");

            
            #line 463 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                         Write(Model.UploadFileName);

            
            #line default
            #line hidden
WriteLiteral(@"'
            if (fileupload!==""""){
                $(""#div_olduploadfile"").show();
            }
            $(""#btn_seoshow"").click(function () {
                $(""#div_seo"").toggle(500);
            });
            $(""#btn_return"").click(function () { CreatePost('");

            
            #line 470 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                        Write(Url.Action("ModelItem"));

            
            #line default
            #line hidden
WriteLiteral("\', { mainid: \'");

            
            #line 470 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                                              Write(Model.ModelID);

            
            #line default
            #line hidden
WriteLiteral("\'});});\r\n            if (\'");

            
            #line 471 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
            Write(Model.ItemID);

            
            #line default
            #line hidden
WriteLiteral("\'>0 && \'");

            
            #line 471 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                 Write(Model.ImageFileName);

            
            #line default
            #line hidden
WriteLiteral("\'!=\'\') {\r\n                $(\'#div_oldfile\').show();\r\n            }\r\n            i" +
"f (\'");

            
            #line 474 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
            Write(Model.ItemID);

            
            #line default
            #line hidden
WriteLiteral("\'>0 && \'");

            
            #line 474 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                 Write(Model.RelateImageName);

            
            #line default
            #line hidden
WriteLiteral(@"'!='') {
                  $('#div_oldrelatefile').show();
            }
            $('#delimage').click(function () {
                $('#div_oldfile').hide();
                $('#ImageFileName').val('');
            });
            $('#delupfile').click(function () {
                $('#div_olduploadfile').hide();
                $('#UploadFileName').val('');
                $('#UploadFilePath').val('');
                $('#UploadFileSize').val('0');
                $('#UploadFileType').val('');
            });

            $('#delrelateimage').click(function () {
                $('#div_oldrelatefile').hide();
                $('#RelateImageName').val('');
            });



            var ckedit = CKEDITOR.replace('HtmlContent', {               
                height: 300,
               filebrowserImageUploadUrl: '");

            
            #line 498 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                      Write(Url.Action("Upload"));

            
            #line default
            #line hidden
WriteLiteral("?command=QuickUpload&type=Images\',\r\n               filebrowserUploadUrl: \'");

            
            #line 499 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                 Write(Url.Action("UploadFile"));

            
            #line default
            #line hidden
WriteLiteral("?command=QuickUpload&type=Files\',\r\n            });\r\n            CKEDITOR.config.e" +
"nterMode = CKEDITOR.ENTER_BR;\r\n            CKEDITOR.config.shiftEnterMode = CKED" +
"ITOR.ENTER_P;\r\n            CKEDITOR.on(\'instanceReady\', function (ev) {\r\n       " +
"         ev.editor.dataProcessor.writer.setRules(\'p\',\r\n                    {\r\n  " +
"                      indent: false,\r\n                        breakBeforeOpen: f" +
"alse,\r\n                        breakAfterOpen: false,\r\n                        b" +
"reakBeforeClose: false,\r\n                        breakAfterClose: false\r\n       " +
"             });\r\n            });\r\n \r\n//            $(\"#btn_active_add\").click(f" +
"unction (evt) {\r\n//                evt.preventDefault();\r\n//                var " +
"html = \'<tr class=\"tr_active\">\';\r\n//                html += \'<td class=\"text-cen" +
"ter\">\'\r\n//                 html += \'<label class=\"mt-checkbox mt-checkbox-single" +
" mt-checkbox-outline\">\'\r\n//                 html += \'<input type=\"checkbox\" clas" +
"s=\"checkboxes active\">\'\r\n//                   html += \'<span></span>\'\r\n//       " +
"            html += \'</label>\'\r\n//                      html += \'</td>\'\r\n//     " +
"               html += \'<td class=\"text-center\">\'\r\n//                    html +=" +
" \' <div class=\"col-md-10 col-sm-12 col-xs-12 bg-white mobile_white\">\'\r\n//       " +
"             html += \'<div class=\"input-group input-large\" style=\"float:left\">\'\r" +
"\n//                html += \'<div class=\"date-picker input-daterange\" data-date-f" +
"ormat=\"yyyy/mm/dd\">\'   \r\n//                     html += `<input class=\"form-cont" +
"rol text-box single-line\" id=\"StDateStr\" name=\"StDateStr\" placeholder=\"開始日期\" rea" +
"donly=\"readonly\" type=\"text\" value=\"\">`                                \r\n//     " +
"                   html += \' </div>\'\r\n//                        html += \'<span c" +
"lass=\"input-group-addon\">to</span>\'\r\n//                        html += \'<div cla" +
"ss=\"date-picker input-daterange\" data-date-format=\"yyyy/mm/dd\">\'\r\n//            " +
"            html += `<input class=\"form-control text-box single-line\" id=\"EdDate" +
"Str\" name=\"EdDateStr\" placeholder=\"結束日期\" readonly=\"readonly\" type=\"text\" value=\"" +
"\">`         \r\n//                          html += \'</div>\'\r\n//                  " +
"       html += \'</div>\'\r\n//                          html += \'<div class=\"\" styl" +
"e=\"float:left; padding-left:5px;\">\'\r\n//                         html += \' <butto" +
"n type=\"button\" class=\"btn blue\" id=\"btn_clear\">清空</button>\'\r\n//                " +
"            html += \' </div>\'\r\n//                               html += \'</div>\'" +
"\r\n//                             html += \'</td>\'\r\n//                html += \'</t" +
"r>\';\r\n//                var row = $(\'#tbl_active>tbody tr\');\r\n////              " +
"  $(row).find(\"input\").removeClass(\"hasDatepicker\").removeAttr(\"id\").datepicker(" +
"{\r\n////       format: \"yyyy/mm/dd\",\r\n////        autoclose: true,\r\n////        l" +
"anguage: \'zh-TW\'\r\n////})\r\n//                  if (row.length == 0) {\r\n//        " +
"            row.append(html);\r\n//                }\r\n//                else {\r\n//" +
"                    row.after(html);\r\n//                }\r\n//            })\r\n   " +
"         $(\'#btn_file_add\').click(function (evt) {\r\n\r\n                evt.preven" +
"tDefault();\r\n\r\n                var html = \'<tr class=\"tr_file\">\';\r\n             " +
"   html += \'   <td class=\"text-center\">\';\r\n                html += \'   <label cl" +
"ass=\"mt-checkbox mt-checkbox-single mt-checkbox-outline\">\';\r\n                htm" +
"l += \'       <input type=\"checkbox\" class=\"checkboxes chksel\">\';\r\n              " +
"  html += \'       <span></span>\';\r\n                html += \'   </label>\';\r\n     " +
"           html += \'   </td>\';\r\n                html += \'   <td class=\"text-cent" +
"er\">\';\r\n                html += \'       <input type=\"file\" id=\"uploadfile\" class" +
"=\"display_inline\" name=\"UploadFile\">\';\r\n                html += \'       <span cl" +
"ass=\"required float_left\">建議檔案大小5MB內</span>\';\r\n                html += \'   </td>" +
"\';\r\n                html += \'   <td class=\"text-left\"> \';\r\n                html " +
"+= \'       <input type=\"text\" name=\"Title\" id=\"Title\" maxlength=\"75\" class=\"form" +
"-control\" >\';\r\n                html += \'       <span class=\"required\" id=\"Title-" +
"error\" style=\"display:none;\">標題說明 必須填寫！</span>\';\r\n                html += \'     " +
"  <div class=\"required\">限制輸入75字內</div>\';\r\n                html += \'   </td>\';\r\n " +
"               html += \'   <td class=\"text-center\">\';\r\n                html += \'" +
"       <input type=\"text\" name=\"UploadFileDesc\" id=\"UploadFileDesc\" maxlength=\"7" +
"5\" class=\"form-control\">\';\r\n                html += \'       <span class=\"require" +
"d\" id=\"UploadFileDesc-error\" style=\"display:none;\">檔案說明 必須填寫！</span>\';\r\n        " +
"        html += \'       <div class=\"red\">限制輸入75字內</div>\'\r\n                html +" +
"= \'   </td>\';\r\n                html += \'</tr>\';\r\n\r\n                if ($(\'#tbl_f" +
"ile>tbody tr\').length == 0) {\r\n                    $(\'#tbl_file>tbody\').append(h" +
"tml);\r\n                }\r\n                else {\r\n                    $(\'#tbl_fi" +
"le>tbody tr:last\').after(html);\r\n                }\r\n\r\n            })\r\n\r\n        " +
"     $(\'#btn_file_del\').click(function () {\r\n                $(\'.chksel:checked\'" +
").parents(\'tr\').remove();\r\n             })\r\n\r\n            $(\'#btn_image_add\').cl" +
"ick(function (evt) {\r\n\r\n                evt.preventDefault();\r\n\r\n               " +
" var html = \'<tr class=\"tr_image\">\';\r\n                html += \'   <td class=\"tex" +
"t-center\">\';\r\n                html += \'   <label class=\"mt-checkbox mt-checkbox-" +
"single mt-checkbox-outline\">\';\r\n                html += \'       <input type=\"che" +
"ckbox\" class=\"checkboxes image\">\';\r\n                html += \'       <span></span" +
">\';\r\n                html += \'   </label>\';\r\n                html += \'   </td>\';" +
"\r\n                html += \'   <td class=\"text-center\">\';\r\n                html +" +
"= \'       <input type=\"file\" id=\"uploadfile\" class=\"display_inline\" name=\"Upload" +
"File\" accept=\"image/*\">\';\r\n                html += \'       <span class=\"required" +
" float_left\">建議檔案大小5MB內</span>\';\r\n                html += \'   </td>\';\r\n         " +
"       html += \'   <td class=\"text-center\">\';\r\n                html += \'   </td>" +
"\';\r\n                html += \'   <td class=\"text-center\">\';\r\n                html" +
" += \'       <input type=\"text\" name=\"UploadFileDesc\" id=\"UploadFileDesc\" maxleng" +
"th=\"75\" class=\"form-control\">\';\r\n                html += \'       <span class=\"re" +
"quired\" id=\"UploadFileDesc-error\" style=\"display:none;\">檔案說明 必須填寫！</span>\';\r\n   " +
"             html += \'       <div class=\"red\">限制輸入75字內</div>\'\r\n                h" +
"tml += \'   </td>\';\r\n                html += \'</tr>\';\r\n\r\n                if ($(\'#" +
"tbl_image>tbody tr\').length == 0) {\r\n                    $(\'#tbl_image>tbody\').a" +
"ppend(html);\r\n                }\r\n                else {\r\n                    $(\'" +
"#tbl_image>tbody tr:last\').after(html);\r\n                }\r\n\r\n            })\r\n\r\n" +
"             $(\'#btn_image_del\').click(function () {\r\n                $(\'.image:" +
"checked\').parents(\'tr\').remove();\r\n             })\r\n\r\n            $(\'#EdDateStr\'" +
").change(function () {\r\n                var new_date = moment($(\'#EdDateStr\').va" +
"l(), \"YYYY/MM/DD\").add(1, \'days\');\r\n                $(\'#UnPublicshStr\').val(new_" +
"date.format(\'YYYY/MM/DD\'));\r\n\r\n            })\r\n            $(\'#editform\').submit" +
"(function (event) {\r\n\r\n               $(\".required\").hide();\r\n                 v" +
"ar inputval = $(\"#form-body2 :input\").filter(function () { return $(this).val() " +
"== \"\" && $(this).hasClass(\'checkitem\'); });\r\n                for (var idx = 0; i" +
"dx < inputval.length; idx++) {\r\n                    $(\"#\" + inputval[idx].name +" +
" \"-error\").show();\r\n                }\r\n                if (inputval.length > 0) " +
"{ return false; }\r\n                var file = $(\"#file_image\");\r\n               " +
" var _validFileExtensions = [\".jpg\", \".png\", \".gif\", \".jpeg\"];\r\n                " +
"var sFileName = file.val();\r\n                if (sFileName.length > 0) {\r\n      " +
"              var blnValid = false;\r\n                    for (var j = 0; j < _va" +
"lidFileExtensions.length; j++) {\r\n                        var sCurExtension = _v" +
"alidFileExtensions[j];\r\n                        if (sFileName.substr(sFileName.l" +
"ength - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtensi" +
"on.toLowerCase()) {\r\n                            blnValid = true;\r\n             " +
"               break;\r\n                        }\r\n                    }\r\n       " +
"             if (!blnValid) {\r\n                        alert(\"只能上傳Image檔案\");\r\n  " +
"                      file.outerHTML = file.outerHTML;\r\n                        " +
"return false;\r\n                    }\r\n                }\r\n\r\n                var r" +
"file = $(\"#file_relateimage\");\r\n                sFileName = rfile.val();\r\n      " +
"          if (sFileName.length > 0) {\r\n                    var blnValid = false;" +
"\r\n                    for (var j = 0; j < _validFileExtensions.length; j++) {\r\n " +
"                       var sCurExtension = _validFileExtensions[j];\r\n           " +
"             if (sFileName.substr(sFileName.length - sCurExtension.length, sCurE" +
"xtension.length).toLowerCase() == sCurExtension.toLowerCase()) {\r\n              " +
"              blnValid = true;\r\n                            break;\r\n            " +
"            }\r\n                    }\r\n                    if (!blnValid) {\r\n    " +
"                    alert(\"相關圖片只能上傳Image檔案\");\r\n                        file.oute" +
"rHTML = file.outerHTML;\r\n                        return false;\r\n                " +
"    }\r\n                }\r\n\r\n               var formData = new FormData();\r\n     " +
"          var array = $(\'#editform\').serializeArray();\r\n               $.each(ar" +
"ray, function () {\r\n                   formData.append(this.name, this.value);\r\n" +
"               });\r\n               formData.append(\"HtmlContent\", _html.encode(C" +
"KEDITOR.instances.HtmlContent.getData()));\r\n                formData.append(\"Tit" +
"le\", _html.encode($(\'#Title\').val()));\r\n\r\n                \r\n                //在這" +
"裡注入資料\r\n                if (typeof InjectData === \'function\') {\r\n                " +
"    formData= InjectData(formData);\r\n                }\r\n               \r\n       " +
"         var iscon = true;\r\n                if ($(\'#LinkUrl\').val() != \"\" && $(\'" +
"#LinkUrlDesc\').val() == \"\") {\r\n                    $(\'#LinkUrlDesc-error\').show(" +
");\r\n                    iscon = false;\r\n                }\r\n                var i" +
"mages = $(\'#file_image\').get(0).files;\r\n                if (images.length > 0) {" +
"\r\n                    formData.append(\"ImageFile\", images[0]);\r\n                " +
"    if ($(\'#ImageFileDesc\').val() == \"\") {\r\n                        $(\'#ImageFil" +
"eDesc-error\').show();\r\n                        iscon = false;\r\n                 " +
"   }\r\n                } else {\r\n                    formData.append(\"ImageFile\"," +
" null);\r\n                    if ($(\'#ImageFileName\').val() != \"\") {\r\n           " +
"             if ($(\'#ImageFileDesc\').val() == \"\") {\r\n                           " +
" $(\'#ImageFileDesc-error\').show();\r\n                            iscon = false;\r\n" +
"                        }\r\n                    }\r\n                }\r\n           " +
"    //\r\n                var rimages = $(\'#file_relateimage\').get(0).files;\r\n    " +
"            if (rimages.length > 0) {\r\n                    formData.append(\"Rela" +
"teImageFile\", rimages[0]);\r\n                } else {\r\n                    formDa" +
"ta.append(\"RelateImageFile\", null);\r\n                }\r\n            var uploadfi" +
"le = $(\'#SingleUploadfile\').get(0).files;\r\n                if (uploadfile.length" +
" > 0) {\r\n                    formData.append(\"UploadFile\", uploadfile[0]);\r\n    " +
"                if ($(\'#SingleUploadFileDesc\').val() == \"\") {\r\n                 " +
"       $(\'#SingleUploadFileDesc-error\').show();\r\n                        iscon =" +
" false;\r\n                    }\r\n                } else {\r\n                    fo" +
"rmData.append(\"UploadFile\", null);\r\n                    if ($(\'#UploadFileName\')" +
".val() != \"\") {\r\n                        if ($(\'#SingleUploadFileDesc\').val() ==" +
" \"\") {\r\n                            $(\'#SingleUploadFileDesc-error\').show();\r\n  " +
"                          iscon = false;\r\n                        }\r\n           " +
"         }\r\n                }\r\n\r\n              if (DateBetweenVaild(\'StDateStr\'," +
"\'EdDateStr\') == false) {\r\n                    alert(\'顯示日期_開始日期必須小於結束日期！\');\r\n    " +
"                return false;\r\n              }\r\n\r\n               if ($(\'#fileDow" +
"nloadItem_LinkUrl\').val() != \"\" && $(\'#fileDownloadItem_LinkUrlDesc\').val() == \'" +
"\') {\r\n                   iscon = false;\r\n                   $(\'#LinkUrlDesc-erro" +
"r\').show();\r\n               }\r\n\r\n            var i = 0;\r\n            $(\'.tr_file" +
"\').each(function () {\r\n                   var uploadfile = $(this).find(\'#upload" +
"file\').get(0).files;\r\n                   if (uploadfile.length > 0) {\r\n         " +
"              formData.append(\"fileDownloadFiles[\" + i + \"].UploadFile\", uploadf" +
"ile[0]);\r\n                       formData.append(\"fileDownloadFiles[\" + i + \"].U" +
"ploadFileDesc\", $(this).find(\'#UploadFileDesc\').val());\r\n                       " +
"formData.append(\"fileDownloadFiles[\" + i + \"].Title\", $(this).find(\'#Title\').val" +
"());\r\n                       if ($(this).find(\'#UploadFileDesc\').val() == \"\") {\r" +
"\n                           $(this).find(\'#UploadFileDesc-error\').show();\r\n     " +
"                      iscon = false;\r\n                       }\r\n                " +
"       if ($(this).find(\'#Title\').val() == \"\") {\r\n                           $(t" +
"his).find(\'#Title-error\').show();\r\n                           iscon = false;\r\n  " +
"                     }\r\n                   } else {\r\n                       form" +
"Data.append(\"fileDownloadFiles[\" + i + \"].UploadFile\", null);\r\n                 " +
"      formData.append(\"fileDownloadFiles[\" + i + \"].UploadFileName\", $(this).fin" +
"d(\'#UploadFileName\').val());\r\n                       formData.append(\"fileDownlo" +
"adFiles[\" + i + \"].UploadFilePath\", $(this).find(\'#UploadFilePath\').val());\r\n   " +
"                    formData.append(\"fileDownloadFiles[\" + i + \"].UploadFileDesc" +
"\", $(this).find(\'#UploadFileDesc\').val());\r\n                       formData.appe" +
"nd(\"fileDownloadFiles[\" + i + \"].UploadFileSize\", $(this).find(\'#UploadFileSize\'" +
").val());\r\n                       formData.append(\"fileDownloadFiles[\" + i + \"]." +
"UploadFileType\", $(this).find(\'#UploadFileType\').val());\r\n                      " +
" formData.append(\"fileDownloadFiles[\" + i + \"].Title\", $(this).find(\'#Title\').va" +
"l());\r\n                       if ($(this).find(\'#UploadFileName\').val() != \"\") {" +
"\r\n                           if ($(this).find(\'#UploadFileDesc\').val() == \"\") {\r" +
"\n                               $(this).find(\'#UploadFileDesc-error\').show();\r\n " +
"                              iscon = false;\r\n                           }\r\n    " +
"                       if ($(this).find(\'#Title\').val() == \"\") {\r\n              " +
"                 $(this).find(\'#Title-error\').show();\r\n                         " +
"      iscon = false;\r\n                           }\r\n                       }\r\n  " +
"                 }\r\n\r\n                   i++;\r\n            })\r\n\r\n            var" +
" i = 0;\r\n            $(\'.tr_image\').each(function () {\r\n                   var u" +
"ploadfile = $(this).find(\'#uploadfile\').get(0).files;\r\n                   if (up" +
"loadfile.length > 0) {\r\n                       formData.append(\"messageImages[\" " +
"+ i + \"].UploadFile\", uploadfile[0]);\r\n                       formData.append(\"m" +
"essageImages[\" + i + \"].UploadFileDesc\", $(this).find(\'#UploadFileDesc\').val());" +
"\r\n                       if ($(this).find(\'#UploadFileDesc\').val() == \"\") {\r\n   " +
"                        $(this).find(\'#UploadFileDesc-error\').show();\r\n         " +
"                  iscon = false;\r\n                       }\r\n                   }" +
" else {\r\n                       formData.append(\"messageImages[\" + i + \"].Upload" +
"File\", null);\r\n                       formData.append(\"messageImages[\" + i + \"]." +
"UploadFileName\", $(this).find(\'#UploadFileName\').val());\r\n                      " +
" formData.append(\"messageImages[\" + i + \"].UploadFilePath\", $(this).find(\'#Uploa" +
"dFilePath\').val());\r\n                       formData.append(\"messageImages[\" + i" +
" + \"].UploadFileDesc\", $(this).find(\'#UploadFileDesc\').val());\r\n                " +
"       if ($(this).find(\'#UploadFileName\').val() != \"\") {\r\n                     " +
"      if ($(this).find(\'#UploadFileDesc\').val() == \"\") {\r\n                      " +
"         $(this).find(\'#UploadFileDesc-error\').show();\r\n                        " +
"       iscon = false;\r\n                           }\r\n                       }\r\n " +
"                  }\r\n\r\n                   i++;\r\n            })\r\n\r\n              " +
"  if (iscon == false) { return false;}\r\n                $.ajax({\r\n              " +
"      url: this.action,\r\n                    data: formData,\r\n                  " +
"  type: \'POST\',\r\n                    cache: false,\r\n                    contentT" +
"ype: false,\r\n                    processData: false,\r\n                    succes" +
"s: function (data) {\r\n                        alert(data);\r\n                    " +
"    if (data == \'新增成功\' || data == \'修改成功\') {\r\n                            CreateP" +
"ost(\'");

            
            #line 824 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                   Write(Url.Action("ModelItem"));

            
            #line default
            #line hidden
WriteLiteral("\', { mainid: \'");

            
            #line 824 "..\..\Areas\webadmin\Views\Message\MessageEdit.cshtml"
                                                                         Write(Model.ModelID);

            
            #line default
            #line hidden
WriteLiteral(@"'});
                        }


                    }, error: function () {
                        // handle error
                    }
                });
                return false;
            });

        });

        function callpreview() {
            var htmlcontent = CKEDITOR.instances.HtmlContent.getData();
            if (htmlcontent == """") { htmlcontent = ""</br>"" }
            bootbox.alert({
                title: ""預覽"",
                message: htmlcontent,
                size: 'large'
            });
        }
    </script>

");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
